<?php

use Illuminate\Database\Seeder;

class communes extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
    			['nom' => 'Adrar','daira_id' => '1'],
    			['nom' => 'Bouda','daira_id' => '1'],
    			['nom' => 'Ouled Ahmed Tammi','daira_id' => '1'],
    			['nom' => 'Akabli','daira_id' => '2'],
    			['nom' => 'Aoulef','daira_id' => '2'],
    			['nom' => 'Tamekten','daira_id' => '2'],
    			['nom' => 'Tit','daira_id' => '2'],
    			['nom' => 'Aougrout','daira_id' => '3'],
    			['nom' => 'Deldoul','daira_id' => '3'],
    			['nom' => 'Metarfa','daira_id' => '3'],
    			['nom' => 'Bordj Badji Mokhtar','daira_id' => '4'],
    			['nom' => 'Timiaouine','daira_id' => '4'],
    			['nom' => 'Charouine','daira_id' => '5'],
    			['nom' => 'Ouled Aïssa','daira_id' => '5'],
    			['nom' => 'Talmine','daira_id' => '5'],
    			['nom' => 'Fenoughil ','daira_id' => '6'],
    			['nom' => 'Tamantit','daira_id' => '6'],
    			['nom' => 'Tamest','daira_id' => '6'],
    			['nom' => 'Reggane','daira_id' => '7'],
    			['nom' => 'Sali','daira_id' => '7'],
    			['nom' => 'Timimoun','daira_id' => '8'],
    			['nom' => 'Ouled Said','daira_id' => '8'],
    			['nom' => 'Ksar Kaddour','daira_id' => '9'],
    			['nom' => 'Tinerkouk','daira_id' => '9'],
    			['nom' => 'Sebaa','daira_id' => '10'],
    			['nom' => 'Tsabit','daira_id' => '10'],
    			['nom' => 'Zaouiet Kounta','daira_id' => '11'],
    			['nom' => 'In Zghmir','daira_id' => '11'],
    			['nom' => 'Chlef','daira_id' => '12'],
    			['nom' => 'Sendjas','daira_id' => '12'],
    			['nom' => 'Oum Drou','daira_id' => '12'],
    			['nom' => 'Abou El Hassan','daira_id' => '13'],
    			['nom' => 'Talassa','daira_id' => '13'],
    			['nom' => 'Tadjena','daira_id' => '13'],
    			['nom' => 'El Karimia','daira_id' => '14'],
    			['nom' => 'Harchoun','daira_id' => '14'],
    			['nom' => 'Beni Bouateb','daira_id' => '14'],
    			['nom' => 'Beni Haoua','daira_id' => '15'],
    			['nom' => 'Breira','daira_id' => '15'],
    			['nom' => 'Oued Goussine','daira_id' => '15'],
    			['nom' => 'Ouled Fares','daira_id' => '16'],
    			['nom' => 'Chettia','daira_id' => '16'],
    			['nom' => 'Labiod Medjadja','daira_id' => '16'],
    			['nom' => 'El Marsa','daira_id' => '17'],
    			['nom' => 'Moussadek','daira_id' => '17'],
    			['nom' => 'Taougrite','daira_id' => '18'],
    			['nom' => 'Dahra','daira_id' => '18'],
    			['nom' => 'Oued Fodda','daira_id' => '19'],
    			['nom' => 'Beni Rached','daira_id' => '19'],
    			['nom' => 'Ouled Abbes','daira_id' => '19'],
    			['nom' => 'Ténès','daira_id' => '20'],
    			['nom' => 'Sidi Akkacha','daira_id' => '20'],
    			['nom' => 'Sidi Abderrahmane','daira_id' => '20'],
    			['nom' => 'Ouled Ben Abdelkader','daira_id' => '21'],
    			['nom' => 'El Hadjadj','daira_id' => '21'],
    			['nom' => 'Aïn Merane','daira_id' => '22'],
    			['nom' => 'Harenfa','daira_id' => '22'],
    			['nom' => 'Boukadir','daira_id' => '23'],
    			['nom' => ' Oued Sly','daira_id' => '23'],
    			['nom' => 'Sobha','daira_id' => '23'],
    			['nom' => 'Zeboudja','daira_id' => '24'],
    			['nom' => 'Bénairia','daira_id' => '24'],
    			['nom' => 'Bouzeghaia','daira_id' => '24'],
    			['nom' => 'Aflou','daira_id' => '25'],
    			['nom' => 'Sebgag','daira_id' => '25'],
    			['nom' => 'Sidi Bouzid','daira_id' => '25'],
    			['nom' => 'Aïn Madhi','daira_id' => '26'],
    			['nom' => 'Tadjemout','daira_id' => '26'],
    			['nom' => 'Tadjrouna','daira_id' => '26'],
    			['nom' => 'El Houaita','daira_id' => '26'],
    			['nom' => 'Kheneg 	','daira_id' => '26'],
    			['nom' => 'Brida','daira_id' => '27'],
    			['nom' => 'Taouila','daira_id' => '27'],
    			['nom' => 'El Ghicha','daira_id' => '28'],
    			['nom' => 'Gueltat Sidi Saad','daira_id' => '29'],
    			['nom' => 'Aïn Sidi Ali','daira_id' => '29'],
    			['nom' => 'Hadj Mechri','daira_id' => '29'],
    			['nom' => 'Beidha','daira_id' => '29'],
    			['nom' => 'Hassi R\'Mel','daira_id' => '30'],
    			['nom' => 'Hassi Delaa','daira_id' => '30'],
    			['nom' => 'Ksar El Hirane','daira_id' => '31'],
    			['nom' => 'Bennasser Benchohra','daira_id' => '31'],
    			['nom' => 'Laghouat','daira_id' => '32'],
    			['nom' => 'Oued Morra','daira_id' => '33'],
    			['nom' => 'Oued M\'Zi','daira_id' => '33'],
    			['nom' => 'Sidi Makhlouf','daira_id' => '34'],
    			['nom' => 'El Assafia','daira_id' => '34'],
    			['nom' => 'Aïn Babouche','daira_id' => '35'],
    			['nom' => 'Aïn Diss','daira_id' => '35'],
    			['nom' => 'Aïn Beïda','daira_id' => '36'],
    			['nom' => 'Zorg','daira_id' => '36'],
    			['nom' => 'Berriche','daira_id' => '36'],
    			['nom' => 'Aïn Fakroun','daira_id' => '37'],
    			['nom' => 'El Fedjouz Boughrara Saoudi','daira_id' => '37'],
    			['nom' => 'Aïn Kercha','daira_id' => '38'],
    			['nom' => 'El Harmilia ','daira_id' => '38'],
    			['nom' => 'Hanchir Toumghani','daira_id' => '38'],
    			['nom' => 'Aïn M\'lila','daira_id' => '39'],
    			['nom' => 'Ouled Gacem','daira_id' => '39'],
    			['nom' => 'Ouled Hamla','daira_id' => '39'],
    			['nom' => 'Dhalâa','daira_id' => '40'],
    			['nom' => 'El Djazia','daira_id' => '40'],
    			['nom' => 'Fkirina ','daira_id' => '41'],
    			['nom' => 'Oued Nini','daira_id' => '41'],
    			['nom' => 'Ksar Sbahi','daira_id' => '42'],
    			['nom' => 'Meskiana','daira_id' => '43'],
    			['nom' => 'Behir Chergui ','daira_id' => '43'],
    			['nom' => 'El Belala','daira_id' => '43'],
    			['nom' => 'Rahia','daira_id' => '43'],
    			['nom' => 'Oum el Bouaghi','daira_id' => '44'],
    			['nom' => 'Aïn Zitoun','daira_id' => '44'],
    			['nom' => 'Sigus','daira_id' => '45'],
    			['nom' => 'El Amiria','daira_id' => '45'],
    			['nom' => 'Souk Naamane','daira_id' => '46'],
    			['nom' => 'Bir Chouhada','daira_id' => '46'],
    			['nom' => 'Ouled Zouaï','daira_id' => '46'],
    			['nom' => 'Aïn Djasser','daira_id' => '47'],
    			['nom' => 'El Hassi','daira_id' => '47'],
    			['nom' => 'Aïn Touta','daira_id' => '48'],
    			['nom' => 'Ben Foudhala El Hakania','daira_id' => '48'],
    			['nom' => 'Maafa','daira_id' => '48'],
    			['nom' => 'Ouled Aouf','daira_id' => '48'],
    			['nom' => 'Arris','daira_id' => '49'],
    			['nom' => 'Tighanimine','daira_id' => '49'],
    			['nom' => 'Barika','daira_id' => '50'],
    			['nom' => 'M\'doukel ','daira_id' => '50'],
    			['nom' => 'Bitam','daira_id' => '50'],
    			['nom' => 'Batna','daira_id' => '51'],
    			['nom' => 'Fesdis','daira_id' => '51'],
    			['nom' => 'Oued Chaaba','daira_id' => '51'],
    			['nom' => 'Bouzina','daira_id' => '52'],
    			['nom' => 'Larbaâ','daira_id' => '52'],
    			['nom' => 'Chemora','daira_id' => '53'],
    			['nom' => 'Boulhilat','daira_id' => '53'],
    			['nom' => 'Djezzar','daira_id' => '54'],
    			['nom' => 'Ouled Ammar','daira_id' => '54'],
    			['nom' => 'Abdelkader Azil','daira_id' => '54'],
    			['nom' => 'El Madher','daira_id' => '55'],
    			['nom' => 'Aïn Yagout','daira_id' => '55'],
    			['nom' => 'Boumia','daira_id' => '55'],
    			['nom' => 'Djerma','daira_id' => '55'],
    			['nom' => 'Ichmoul','daira_id' => '56'],
    			['nom' => 'Foum Toub','daira_id' => '56'],
    			['nom' => 'Inoughissen','daira_id' => '56'],
    			['nom' => 'Menaa','daira_id' => '57'],
    			['nom' => 'Tigherghar','daira_id' => '57'],
    			['nom' => 'Merouana ','daira_id' => '58'],
    			['nom' => 'Oued El Ma','daira_id' => '58'],
    			['nom' => 'Ksar Belezma','daira_id' => '58'],
    			['nom' => 'Hidoussa','daira_id' => '58'],
    			['nom' => 'N\'Gaous','daira_id' => '59'],
    			['nom' => 'Boumagueur','daira_id' => '59'],
    			['nom' => 'Sefiane','daira_id' => '59'],
    			['nom' => 'Ouled Si Slimane','daira_id' => '60'],
    			['nom' => 'Taxlent','daira_id' => '60'],
    			['nom' => 'Lemsane','daira_id' => '60'],
    			['nom' => 'Ras Ei Aioun','daira_id' => '61'],
    			['nom' => 'Gosbat  ','daira_id' => '61'],
    			['nom' => 'Guigba','daira_id' => '61'],
    			['nom' => 'Rahbat','daira_id' => '61'],
    			['nom' => 'Talkhamet','daira_id' => '61'],
    			['nom' => 'Ouled Sellam','daira_id' => '61'],
    			['nom' => 'Seggana','daira_id' => '62'],
    			['nom' => 'Tilatou','daira_id' => '62'],
    			['nom' => 'Seriana','daira_id' => '63'],
    			['nom' => 'Lazrou','daira_id' => '63'],
    			['nom' => 'Zanat El Beida','daira_id' => '63'],
    			['nom' => 'Tazoult','daira_id' => '64'],
    			['nom' => 'Ouyoun El Assafir','daira_id' => '64'],
    			['nom' => 'Teniet El Abed','daira_id' => '65'],
    			['nom' => ' Oued Taga','daira_id' => '65'],
    			['nom' => 'Chir','daira_id' => '65'],
    			['nom' => 'Timgad','daira_id' => '66'],
    			['nom' => 'Ouled Fadel','daira_id' => '66'],
    			['nom' => 'T\'Kout','daira_id' => '67'],
    			['nom' => 'Kimmel','daira_id' => '67'],
    			['nom' => 'Ghassira','daira_id' => '67'],
    			['nom' => 'Adekar','daira_id' => '68'],
    			['nom' => 'Taourirt Ighil','daira_id' => '68'],
    			['nom' => 'Beni Ksila','daira_id' => '68'],
    			['nom' => 'Akbou','daira_id' => '68'],
    			['nom' => 'Chellata','daira_id' => '69'],
    			['nom' => 'Ighram','daira_id' => '69'],
    			['nom' => 'Tamokra','daira_id' => '69'],
    			['nom' => 'Amizour ','daira_id' => '70'],
    			['nom' => 'Beni Djellil ','daira_id' => '70'],
    			['nom' => 'Semaoun','daira_id' => '70'],
    			['nom' => 'Ferraoun','daira_id' => '70'],
    			['nom' => 'Aokas','daira_id' => '71'],
    			['nom' => 'Tizi N\'Berber','daira_id' => '71'],
    			['nom' => 'Barbacha','daira_id' => '72'],
    			['nom' => 'Kendira','daira_id' => '72'],
    			['nom' => 'Béjaïa','daira_id' => '73'],
    			['nom' => 'Oued Ghir','daira_id' => '73'],
    			['nom' => 'Beni Maouche','daira_id' => '74'],
    			['nom' => 'Chemini','daira_id' => '75'],
    			['nom' => 'Tibane','daira_id' => '75'],
    			['nom' => 'Souk-Oufella','daira_id' => '75'],
    			['nom' => 'Akfadou','daira_id' => '75'],
    			['nom' => 'Darguina','daira_id' => '76'],
    			['nom' => 'Aït-Smail','daira_id' => '76'],
    			['nom' => 'Taskriout','daira_id' => '76'],
    			['nom' => 'El Kseur','daira_id' => '77'],
    			['nom' => 'Fenaïa Ilmaten','daira_id' => '77'],
    			['nom' => 'Toudja','daira_id' => '77'],
    			['nom' => 'Ighil Ali','daira_id' => '78'],
    			['nom' => 'Aït-R\'zine','daira_id' => '78'],
    			['nom' => 'Kherrata','daira_id' => '79'],
    			['nom' => 'Draâ El-Kaïd','daira_id' => '79'],
    			['nom' => 'Ouzellaguen','daira_id' => '80'],
    			['nom' => 'Amalou','daira_id' => '81'],
    			['nom' => 'M\'cisna','daira_id' => '81'],
    			['nom' => 'Bouhamza ','daira_id' => '81'],
    			['nom' => 'Seddouk','daira_id' => '81'],
    			['nom' => 'Sidi-Aïch','daira_id' => '82'],
    			['nom' => 'Leflaye','daira_id' => '82'],
    			['nom' => 'Tinabdher','daira_id' => '82'],
    			['nom' => 'Tifra','daira_id' => '82'],
    			['nom' => 'Sidi Ayad','daira_id' => '82'],
    			['nom' => 'Melbou','daira_id' => '83'],
    			['nom' => 'Souk El Ténine','daira_id' => '83'],
    			['nom' => 'Tamridjet','daira_id' => '83'],
    			['nom' => 'Tazmalt','daira_id' => '84'],
    			['nom' => 'Beni Mellikeche','daira_id' => '84'],
    			['nom' => 'Boudjellil','daira_id' => '84'],
    			['nom' => 'Boukhelifa','daira_id' => '85'],
    			['nom' => 'Tichy','daira_id' => '85'],
    			['nom' => 'Tala Hamza','daira_id' => '85'],
    			['nom' => 'Timezrit','daira_id' => '86'],
    			['nom' => 'Biskra','daira_id' => '87'],
    			['nom' => 'El Hadjeb','daira_id' => '87'],
    			['nom' => 'Djemorah','daira_id' => '88'],
    			['nom' => 'Branis','daira_id' => '88'],
    			['nom' => 'El Kantara','daira_id' => '89'],
    			['nom' => 'Aïn Zaatout','daira_id' => '89'],
    			['nom' => 'M\'chouneche','daira_id' => '90'],
    			['nom' => 'Sidi Okba','daira_id' => '91'],
    			['nom' => 'Chetma','daira_id' => '91'],
    			['nom' => 'El Haouch','daira_id' => '91'],
    			['nom' => 'Aïn Naga','daira_id' => '91'],
    			['nom' => 'Zeribet El Oued','daira_id' => '92'],
    			['nom' => 'El Mizaraa','daira_id' => '92'],
    			['nom' => 'El Feidh','daira_id' => '92'],
    			['nom' => 'Khenguet Sidi Nadji','daira_id' => '92'],
    			['nom' => 'Ourlal','daira_id' => '93'],
    			['nom' => 'Lioua','daira_id' => '93'],
    			['nom' => 'Oumache','daira_id' => '93'],
    			['nom' => 'Mekhadma','daira_id' => '93'],
    			['nom' => 'M\'Lili','daira_id' => '93'],
    			['nom' => 'Tolga','daira_id' => '94'],
    			['nom' => 'Bouchagroune','daira_id' => '94'],
    			['nom' => 'Bordj Ben Azzouz','daira_id' => '94'],
    			['nom' => 'Lichana','daira_id' => '94'],
    			['nom' => 'Ouled Djellal','daira_id' => '95'],
    			['nom' => 'Ech Chaïba','daira_id' => '95'],
    			['nom' => 'Daoussen','daira_id' => '95'],
    			['nom' => 'Sidi Khaled','daira_id' => '96'],
    			['nom' => 'Besbes','daira_id' => '96'],
    			['nom' => 'Ras El Miaad','daira_id' => '96'],
    			['nom' => 'Foughala','daira_id' => '97'],
    			['nom' => 'El Ghrous','daira_id' => '97'],
    			['nom' => 'El Outaya (Loutaya)','daira_id' => '98'],
    			['nom' => 'Béchar','daira_id' => '99'],
    			['nom' => 'Beni Ounif','daira_id' => '100'],
    			['nom' => 'Boukais','daira_id' => '101'],
    			['nom' => 'Lahmar','daira_id' => '101'],
    			['nom' => 'Mougheul','daira_id' => '101'],
    			['nom' => 'Kenadsa','daira_id' => '102'],
    			['nom' => 'Meridja','daira_id' => '102'],
    			['nom' => 'Taghit','daira_id' => '103'],
    			['nom' => 'Abadla','daira_id' => '104'],
    			['nom' => 'Erg Ferradj','daira_id' => '104'],
    			['nom' => 'Mechraa ','daira_id' => '104'],
    			['nom' => 'Houari Boumedienne','daira_id' => '104'],
    			['nom' => 'Tabelbala','daira_id' => '105'],
    			['nom' => 'Igli','daira_id' => '106'],
    			['nom' => 'Beni Abbes','daira_id' => '107'],
    			['nom' => 'Tamtert','daira_id' => '107'],
    			['nom' => 'El Ouata','daira_id' => '108'],
    			['nom' => 'Beni Ikhlef','daira_id' => '109'],
    			['nom' => 'Kerzaz','daira_id' => '109'],
    			['nom' => 'Timoudi','daira_id' => '109'],
    			['nom' => 'Ksabi ','daira_id' => '110'],
    			['nom' => 'Ouled Khoudir','daira_id' => '110'],
    			['nom' => 'Blida','daira_id' => '111'],
    			['nom' => 'Bouarfa ','daira_id' => '111'],
    			['nom' => 'Boufarik','daira_id' => '112'],
    			['nom' => 'Soumaa ','daira_id' => '112'],
    			['nom' => 'Guerouaou','daira_id' => '112'],
    			['nom' => 'Bougara','daira_id' => '113'],
    			['nom' => 'Hammam Melouane','daira_id' => '113'],
    			['nom' => 'Ouled Slama','daira_id' => '113'],
    			['nom' => 'Bouinan','daira_id' => '114'],
    			['nom' => 'Chebli','daira_id' => '114'],
    			['nom' => 'El Affroun','daira_id' => '115'],
    			['nom' => 'Oued Djer','daira_id' => '115'],
    			['nom' => 'Larbaa ','daira_id' => '116'],
    			['nom' => 'Souhane','daira_id' => '116'],
    			['nom' => 'Meftah','daira_id' => '117'],
    			['nom' => 'Djebabra','daira_id' => '117'],
    			['nom' => 'Mouzaia','daira_id' => '118'],
    			['nom' => 'Chiffa','daira_id' => '118'],
    			['nom' => 'Aïn Romana','daira_id' => '118'],
    			['nom' => 'Oued Alleug','daira_id' => '119'],
    			['nom' => 'Beni Tamou','daira_id' => '119'],
    			['nom' => 'Benkhelil','daira_id' => '119'],
    			['nom' => 'Ouled Yaich','daira_id' => '120'],
    			['nom' => 'Chréa','daira_id' => '120'],
    			['nom' => 'Beni Mered','daira_id' => '120'],
    			['nom' => 'Bouira','daira_id' => '121'],
    			['nom' => 'Aïn El Turc','daira_id' => '121'],
    			['nom' => 'Aït Laziz','daira_id' => '121'],
    			['nom' => 'Haizer','daira_id' => '122'],
    			['nom' => 'Taghzout','daira_id' => '122'],
    			['nom' => 'Bechloul','daira_id' => '123'],
    			['nom' => 'El Asnam','daira_id' => '123'],
    			['nom' => 'El Adjiba','daira_id' => '123'],
    			['nom' => 'Ahl El Ksar','daira_id' => '123'],
    			['nom' => 'Ouled Rached','daira_id' => '123'],
    			['nom' => 'M\'Chedallah','daira_id' => '124'],
    			['nom' => 'Saharidj','daira_id' => '124'],
    			['nom' => 'Chorfa ','daira_id' => '124'],
    			['nom' => 'Hanif','daira_id' => '124'],
    			['nom' => 'Aghbalou ','daira_id' => '124'],
    			['nom' => 'Ath Mansour','daira_id' => '124'],
    			['nom' => 'Kadiria','daira_id' => '125'],
    			['nom' => 'Aomar','daira_id' => '125'],
    			['nom' => 'Djebahia','daira_id' => '125'],
    			['nom' => 'Lakhdaria','daira_id' => '126'],
    			['nom' => 'Boukram','daira_id' => '126'],
    			['nom' => 'Maala','daira_id' => '126'],
    			['nom' => 'Bouderbala','daira_id' => '126'],
    			['nom' => 'Zbarbar','daira_id' => '126'],
    			['nom' => 'Guerrouma','daira_id' => '126'],
    			['nom' => 'Bir Ghbalou','daira_id' => '127'],
    			['nom' => 'Raouraoua','daira_id' => '127'],
    			['nom' => 'El Khabouzia','daira_id' => '127'],
    			['nom' => 'Aïn Bessem','daira_id' => '128'],
    			['nom' => 'Ain Laloui ','daira_id' => '128'],
    			['nom' => 'Aïn El Hadjar','daira_id' => '128'],
    			['nom' => 'Souk El Khemis','daira_id' => '129'],
    			['nom' => 'El Mokrani','daira_id' => '129'],
    			['nom' => 'El Hachimia','daira_id' => '130'],
    			['nom' => 'Oued El Berdi','daira_id' => '130'],
    			['nom' => 'Sour El-Ghozlane','daira_id' => '131'],
    			['nom' => 'Maamora','daira_id' => '131'],
    			['nom' => 'Ridane','daira_id' => '131'],
    			['nom' => 'El Hakimia ','daira_id' => '131'],
    			['nom' => 'Dechmia ','daira_id' => '131'],
    			['nom' => 'Dirrah','daira_id' => '131'],
    			['nom' => 'Bordj Okhriss','daira_id' => '132'],
    			['nom' => 'Mezdour','daira_id' => '132'],
    			['nom' => 'Taguedit','daira_id' => '132'],
    			['nom' => 'Hadjera Zerga','daira_id' => '132'],
    			['nom' => 'Abalessa','daira_id' => '133'],
    			['nom' => 'In Ghar','daira_id' => '134'],
    			['nom' => 'In Guezzam','daira_id' => '135'],
    			['nom' => 'In Salah','daira_id' => '136'],
    			['nom' => 'Foggaret Ezzaouia','daira_id' => '136'],
    			['nom' => 'Tazrouk','daira_id' => '137'],
    			['nom' => 'Idles','daira_id' => '137'],
    			['nom' => 'Tamanrasset','daira_id' => '138'],
    			['nom' => 'In Amguel','daira_id' => '138'],
    			['nom' => 'Tinzaouten','daira_id' => '139'],
    			['nom' => 'Tébessa','daira_id' => '141'],
    			['nom' => 'Bekkaria','daira_id' => '142'],
    			['nom' => 'Boulhaf Dir','daira_id' => '142'],
    			['nom' => 'El Kouif','daira_id' => '142'],
    			['nom' => 'Bir Dheb','daira_id' => '143'],
    			['nom' => 'Morsott','daira_id' => '143'],
    			['nom' => 'El Houidjbet','daira_id' => '144'],
    			['nom' => 'El Ma Labiodh','daira_id' => '144'],
    			['nom' => 'Boukhadra','daira_id' => '145'],
    			['nom' => 'El Aouinet','daira_id' => '145'],
    			['nom' => 'Aïn Zerga','daira_id' => '146'],
    			['nom' => 'El Meridj','daira_id' => '146'],
    			['nom' => 'Ouenza','daira_id' => '146'],
    			['nom' => 'Hammamet','daira_id' => '147'],
    			['nom' => 'Guorriguer','daira_id' => '147'],
    			['nom' => 'Bir Mokkadem','daira_id' => '147'],
    			['nom' => 'Ogla Melha','daira_id' => '148'],
    			['nom' => 'Bir el-Ater','daira_id' => '148'],
    			['nom' => 'El Mezeraa','daira_id' => '149'],
    			['nom' => 'Bedjene','daira_id' => '149'],
    			['nom' => 'Stah Guentis','daira_id' => '149'],
    			['nom' => 'El Ogla','daira_id' => '149'],
    			['nom' => 'Safsaf El Ouesra','daira_id' => '150'],
    			['nom' => 'Oum Ali','daira_id' => '150'],
    			['nom' => 'Ferkane','daira_id' => '151'],
    			['nom' => 'Negrine','daira_id' => '151'],
    			['nom' => 'Tlidjene','daira_id' => '152'],
    			['nom' => 'Cheria','daira_id' => '152'],
    			['nom' => 'Aïn Nehala','daira_id' => '153'],
    			['nom' => 'Aïn Tallout','daira_id' => '153'],
    			['nom' => 'Bab El Assa','daira_id' => '154'],
    			['nom' => 'Souani','daira_id' => '154'],
    			['nom' => 'Souk Tlata','daira_id' => '154'],
    			['nom' => 'Hennaya','daira_id' => '155'],
    			['nom' => 'Ouled Riyah','daira_id' => '155'],
    			['nom' => 'Zenata','daira_id' => '155'],
    			['nom' => 'Beni Boussaid','daira_id' => '156'],
    			['nom' => 'Sidi Medjahed','daira_id' => '156'],
    			['nom' => 'Beni Khellad','daira_id' => '157'],
    			['nom' => 'Honaïne','daira_id' => '157'],
    			['nom' => 'Azaïls','daira_id' => '158'],
    			['nom' => 'Beni Bahdel','daira_id' => '158'],
    			['nom' => 'Beni Snous','daira_id' => '158'],
    			['nom' => 'Bensekrane','daira_id' => '159'],
    			['nom' => 'Sidi Abdelli','daira_id' => '159'],
    			['nom' => 'Aïn Fezza','daira_id' => '160'],
    			['nom' => 'Amieur ','daira_id' => '160'],
    			['nom' => 'Chetouane','daira_id' => '160'],
    			['nom' => 'Aïn Fetah','daira_id' => '161'],
    			['nom' => 'Fellaoucene','daira_id' => '161'],
    			['nom' => 'Aïn Kebira','daira_id' => '161'],
    			['nom' => 'Dar Yaghmouracene','daira_id' => '162'],
    			['nom' => 'Ghazaouet ','daira_id' => '162'],
    			['nom' => 'Souahlia','daira_id' => '162'],
    			['nom' => 'Tienet','daira_id' => '162'],
    			['nom' => 'Hammam Boughrara','daira_id' => '163'],
    			['nom' => 'Maghnia','daira_id' => '163'],
    			['nom' => 'Aïn Ghoraba','daira_id' => '164'],
    			['nom' => 'Beni Mester','daira_id' => '164'],
    			['nom' => 'Mansourah ','daira_id' => '164'],
    			['nom' => 'Terny Beni Hdiel','daira_id' => '164'],
    			['nom' => 'Marsa Ben M\'Hidi','daira_id' => '165'],
    			['nom' => 'MSirda Fouaga','daira_id' => '165'],
    			['nom' => 'Djebala ','daira_id' => '166'],
    			['nom' => 'Nedroma','daira_id' => '166'],
    			['nom' => 'Beni Semiel','daira_id' => '167'],
    			['nom' => 'Oued Lakhdar','daira_id' => '167'],
    			['nom' => 'Ouled Mimoun','daira_id' => '167'],
    			['nom' => 'Aïn Youcef','daira_id' => '168'],
    			['nom' => 'Beni Ouarsous','daira_id' => '168'],
    			['nom' => 'El Fehoul','daira_id' => '168'],
    			['nom' => 'Remchi','daira_id' => '168'],
    			['nom' => 'Sebaa Chioukh','daira_id' => '168'],
    			['nom' => 'Bouhlou','daira_id' => '169'],
    			['nom' => 'Sabra','daira_id' => '169'],
    			['nom' => 'El Aricha','daira_id' => '170'],
    			['nom' => 'El Gor','daira_id' => '170'],
    			['nom' => 'Sebdou','daira_id' => '170'],
    			['nom' => 'El Bouihi','daira_id' => '171'],
    			['nom' => 'Sidi Djillali','daira_id' => '171'],
    			['nom' => 'Tlemcen','daira_id' => '172'],
    			['nom' => 'Aïn Deheb','daira_id' => '173'],
    			['nom' => 'Chehaima','daira_id' => '173'],
    			['nom' => 'Naima','daira_id' => '173'],
    			['nom' => 'Aïn Kermes','daira_id' => '174'],
    			['nom' => 'Madna','daira_id' => '174'],
    			['nom' => 'Medrissa','daira_id' => '174'],
    			['nom' => 'Djebilet Rosfa','daira_id' => '174'],
    			['nom' => 'Sidi Abderrahmane','daira_id' => '174'],
    			['nom' => 'Dahmouni','daira_id' => '175'],
    			['nom' => 'Aïn Bouchekif','daira_id' => '175'],
    			['nom' => 'Frenda','daira_id' => '176'],
    			['nom' => 'Aïn El Hadid ','daira_id' => '176'],
    			['nom' => 'Takhemaret','daira_id' => '176'],
    			['nom' => 'Hamadia','daira_id' => '177'],
    			['nom' => 'Bougara','daira_id' => '177'],
    			['nom' => 'Rechaiga','daira_id' => '177'],
    			['nom' => 'Ksar Chellala','daira_id' => '178'],
    			['nom' => 'Serghine','daira_id' => '178'],
    			['nom' => 'Zmalet El Emir Abdelkader','daira_id' => '178'],
    			['nom' => 'Mahdia','daira_id' => '179'],
    			['nom' => 'Aïn Zarit','daira_id' => '179'],
    			['nom' => 'Nadorah','daira_id' => '179'],
    			['nom' => 'Sebaïne','daira_id' => '179'],
    			['nom' => 'Mechraa Safa','daira_id' => '180'],
    			['nom' => 'Djillali Ben Amar','daira_id' => '180'],
    			['nom' => 'Tagdemt','daira_id' => '180'],
    			['nom' => 'Medroussa','daira_id' => '181'],
    			['nom' => 'Sidi Bakhti','daira_id' => '181'],
    			['nom' => 'Mellakou','daira_id' => '181'],
    			['nom' => 'Meghila','daira_id' => '182'],
    			['nom' => 'Sebt','daira_id' => '182'],
    			['nom' => 'Sidi Hosni','daira_id' => '182'],
    			['nom' => 'Oued Lilli','daira_id' => '183'],
    			['nom' => 'Sidi Ali Mellal','daira_id' => '183'],
    			['nom' => 'Tidda','daira_id' => '183'],
    			['nom' => 'Rahouia ','daira_id' => '184'],
    			['nom' => 'Guertoufa','daira_id' => '184'],
    			['nom' => 'Sougueur','daira_id' => '185'],
    			['nom' => 'Faidja','daira_id' => '185'],
    			['nom' => 'Si Abdelghani','daira_id' => '185'],
    			['nom' => 'Tousnina','daira_id' => '185'],
    			['nom' => 'Tiaret','daira_id' => '186'],
    			['nom' => 'Abi Youcef','daira_id' => '187'],
    			['nom' => 'Ain El Hammam','daira_id' => '187'],
    			['nom' => 'Aït Yahia ','daira_id' => '187'],
    			['nom' => 'Akbil','daira_id' => '187'],
    			['nom' => 'Azazga','daira_id' => '188'],
    			['nom' => 'Freha','daira_id' => '188'],
    			['nom' => 'Ifigha','daira_id' => '188'],
    			['nom' => 'Yakouren','daira_id' => '188'],
    			['nom' => 'Zekri','daira_id' => '188'],
    			['nom' => 'Aghribs','daira_id' => '189'],
    			['nom' => 'Aït Chafâa ','daira_id' => '189'],
    			['nom' => 'Akerrou','daira_id' => '189'],
    			['nom' => 'Azeffoun','daira_id' => '189'],
    			['nom' => 'Aït Mahmoud','daira_id' => '190'],
    			['nom' => 'Aït Aissi','daira_id' => '190'],
    			['nom' => 'Aït Douala','daira_id' => '190'],
    			['nom' => 'Aït Zmenzer','daira_id' => '190'],
    			['nom' => 'Aït Yenni','daira_id' => '191'],
    			['nom' => 'Iboudraren','daira_id' => '191'],
    			['nom' => 'Yatafen','daira_id' => '191'],
    			['nom' => 'Assi Youcef','daira_id' => '192'],
    			['nom' => 'Boghni ','daira_id' => '192'],
    			['nom' => 'Bounouh','daira_id' => '192'],
    			['nom' => 'Mechtras','daira_id' => '192'],
    			['nom' => 'Aït Ziki ','daira_id' => '193'],
    			['nom' => 'Bouzeguène','daira_id' => '193'],
    			['nom' => 'Idjeur ','daira_id' => '193'],
    			['nom' => 'Illoula Oumalou','daira_id' => '193'],
    			['nom' => 'Draâ Ben Khedda','daira_id' => '194'],
    			['nom' => 'Sidi Namane','daira_id' => '194'],
    			['nom' => 'Tadmaït','daira_id' => '194'],
    			['nom' => 'Tirmitine','daira_id' => '194'],
    			['nom' => 'Aïn Zaouia','daira_id' => '195'],
    			['nom' => 'Aït Yahia Moussa','daira_id' => '195'],
    			['nom' => 'Draâ El Mizan','daira_id' => '195'],
    			['nom' => 'Frikat','daira_id' => '195'],
    			['nom' => 'Iferhounène','daira_id' => '196'],
    			['nom' => 'Illilten','daira_id' => '196'],
    			['nom' => 'Imsouhel','daira_id' => '196'],
    			['nom' => 'Aït Aggouacha','daira_id' => '197'],
    			['nom' => 'Irdjen','daira_id' => '197'],
    			['nom' => 'Larbaâ Nath Irathen','daira_id' => '197'],
    			['nom' => 'Mâatkas','daira_id' => '198'],
    			['nom' => 'Souk El Thenine','daira_id' => '198'],
    			['nom' => 'Boudjima','daira_id' => '199'],
    			['nom' => 'Makouda','daira_id' => '199'],
    			['nom' => 'Aït Khellili','daira_id' => '200'],
    			['nom' => 'Mekla','daira_id' => '200'],
    			['nom' => 'Souamaâ','daira_id' => '200'],
    			['nom' => 'Aït Boumahdi','daira_id' => '201'],
    			['nom' => 'Aït Toudert','daira_id' => '201'],
    			['nom' => 'Ouacif','daira_id' => '201'],
    			['nom' => 'Agouni Gueghrane','daira_id' => '202'],
    			['nom' => 'Aït Bouadou','daira_id' => '202'],
    			['nom' => 'Tizi N\'Tleta','daira_id' => '202'],
    			['nom' => 'Ouadhia','daira_id' => '202'],
    			['nom' => 'Aït Aissa Mimoun','daira_id' => '203'],
    			['nom' => 'Ouaguenoun','daira_id' => '203'],
    			['nom' => 'Timizart','daira_id' => '203'],
    			['nom' => 'Iflissen','daira_id' => '204'],
    			['nom' => 'Mizrana','daira_id' => '204'],
    			['nom' => 'Tigzirt','daira_id' => '204'],
    			['nom' => 'Imkiren','daira_id' => '205'],
    			['nom' => 'Tizi Gheniff','daira_id' => '205'],
    			['nom' => 'Tizi Ouzou','daira_id' => '206'],
    			['nom' => 'Aït Oumalou','daira_id' => '207'],
    			['nom' => 'Tizi Rached','daira_id' => '207'],
    			['nom' => 'Bab El-Oued','daira_id' => '208'],
    			['nom' => 'Casbah','daira_id' => '208'],
    			['nom' => 'Bologhine','daira_id' => '208'],
    			['nom' => 'Oued Koriche','daira_id' => '208'],
    			['nom' => 'Raïs Hamidou','daira_id' => '208'],
    			['nom' => 'El Hammamet ','daira_id' => '208'],
    			['nom' => 'Baraki','daira_id' => '209'],
    			['nom' => 'Les Eucalyptus','daira_id' => '209'],
    			['nom' => 'Sidi Moussa','daira_id' => '209'],
    			['nom' => 'Bir Mourad Raïs','daira_id' => '210'],
    			['nom' => 'Birkhadem','daira_id' => '210'],
    			['nom' => 'Gue de Constantine','daira_id' => '210'],
    			['nom' => 'Hydra','daira_id' => '210'],
    			['nom' => 'Saoula','daira_id' => '210'],
    			['nom' => 'Birtouta','daira_id' => '211'],
    			['nom' => 'Ouled Chebel ','daira_id' => '211'],
    			['nom' => 'Tessala El Merdja','daira_id' => '211'],
    			['nom' => 'Ben Aknoun','daira_id' => '212'],
    			['nom' => 'Beni Messous','daira_id' => '212'],
    			['nom' => ' Bouzareah','daira_id' => '212'],
    			['nom' => 'El-Biar','daira_id' => '212'],
    			['nom' => 'Aïn Benian ','daira_id' => '213'],
    			['nom' => 'Cheraga','daira_id' => '213'],
    			['nom' => 'Dely Ibrahim','daira_id' => '213'],
    			['nom' => 'Ouled Fayet','daira_id' => '213'],
    			['nom' => 'Aïn Taya','daira_id' => '214'],
    			['nom' => 'Bab Ezzouar','daira_id' => '214'],
    			['nom' => 'Bordj El Bahri','daira_id' => '214'],
    			['nom' => 'Bordj El Kiffan','daira_id' => '214'],
    			['nom' => 'Dar El Beïda','daira_id' => '214'],
    			['nom' => 'El Marsa','daira_id' => '214'],
    			['nom' => 'Mohammadia','daira_id' => '214'],
    			['nom' => 'Baba Hassen','daira_id' => '215'],
    			['nom' => 'Douera','daira_id' => '215'],
    			['nom' => 'Draria','daira_id' => '215'],
    			['nom' => 'El Achour','daira_id' => '215'],
    			['nom' => 'Khraïssia','daira_id' => '215'],
    			['nom' => 'Bachdjerrah','daira_id' => '216'],
    			['nom' => 'Bourouba','daira_id' => '216'],
    			['nom' => 'El Harrach','daira_id' => '216'],
    			['nom' => 'Oued Smar','daira_id' => '216'],
    			['nom' => 'Belouizdad','daira_id' => '217'],
    			['nom' => 'El Magharia','daira_id' => '217'],
    			['nom' => 'Hussein Dey','daira_id' => '217'],
    			['nom' => 'Kouba','daira_id' => '217'],
    			['nom' => 'H\'raoua','daira_id' => '218'],
    			['nom' => 'Reghaïa','daira_id' => '218'],
    			['nom' => 'Rouïba','daira_id' => '218'],
    			['nom' => 'Alger-Centre','daira_id' => '219'],
    			['nom' => 'El Madania','daira_id' => '219'],
    			['nom' => 'El Mouradia','daira_id' => '219'],
    			['nom' => 'Sidi M\'Hamed','daira_id' => '219'],
    			['nom' => 'Mahelma','daira_id' => '220'],
    			['nom' => 'Rahmania ','daira_id' => '220'],
    			['nom' => 'Souidania ','daira_id' => '220'],
    			['nom' => 'Staoueli','daira_id' => '220'],
    			['nom' => 'Zeralda','daira_id' => '220'],
    			['nom' => 'Djelfa','daira_id' => '221'],
    			['nom' => 'Aïn El Ibel','daira_id' => '222'],
    			['nom' => 'Moudjebara','daira_id' => '222'],
    			['nom' => 'Tadmit','daira_id' => '222'],
    			['nom' => 'Zaccar','daira_id' => '222'],
   			  ['nom' => 'Aïn Oussara','daira_id' => '223'],
    			['nom' => 'Guernini','daira_id' => '223'],
    			['nom' => 'Birine','daira_id' => '224'],
    			['nom' => 'Benhar','daira_id' => '224'],
    			['nom' => 'Hassi Bahbah','daira_id' => '225'],
    			['nom' => 'Zaafrane','daira_id' => '225'],
   			  ['nom' => 'Hassi El Euch','daira_id' => '225'],
    			['nom' => 'Aïn Maabed','daira_id' => '225'],
    			['nom' => 'Charef','daira_id' => '226'],
    			['nom' => 'El Guedid','daira_id' => '226'],
    			['nom' => 'Beni Yagoub','daira_id' => '226'],
    			['nom' => 'Dar Chioukh','daira_id' => '227'],
    			['nom' => 'M\'Liliha','daira_id' => '227'],
    			['nom' => 'Sidi Baizid','daira_id' => '227'],
    			['nom' => 'El Idrissia','daira_id' => '228'],
    			['nom' => 'Douis','daira_id' => '228'],
    			['nom' => 'Ain Chouhada','daira_id' => '228'],
    			['nom' => 'Faidh El Botma','daira_id' => '229'],
    			['nom' => 'Amourah','daira_id' => '229'],
    			['nom' => 'Oum Laadham','daira_id' => '229'],
    			['nom' => 'Had-Sahary','daira_id' => '230'],
    			['nom' => 'Bouira Lahdab','daira_id' => '230'],
    			['nom' => 'Aïn Feka','daira_id' => '230'],
    			['nom' => 'Messaad','daira_id' => '231'],
    			['nom' => 'Deldoul ','daira_id' => '231'],
    			['nom' => 'Selmana','daira_id' => '231'],
    			['nom' => 'Sed Rahal','daira_id' => '231'],
    			['nom' => 'Guettara','daira_id' => '231'],
    			['nom' => 'Sidi Ladjel','daira_id' => '232'],
    			['nom' => 'El Khemis','daira_id' => '232'],
    			['nom' => 'Hassi Fedoul','daira_id' => '232'],
   			  ['nom' => 'Bordj Tahar','daira_id' => '233'],
    			['nom' => 'Chekfa','daira_id' => '233'],
    			['nom' => 'El Kennar Nouchfi ','daira_id' => '233'],
    			['nom' => 'Sidi Abdelaziz','daira_id' => '233'],
    			['nom' => 'Boudriaa Ben Yadjis','daira_id' => '234'],
    			['nom' => 'Djimla','daira_id' => '234'],
    			['nom' => 'Djemaa Beni Habibi','daira_id' => '235'],
    			['nom' => 'Bouraoui Belhadef ','daira_id' => '235'],
    			['nom' => 'El Ancer','daira_id' => '235'],
    			['nom' => 'Kheïri Oued Adjoul','daira_id' => '235'],
    			['nom' => 'El Aouana','daira_id' => '236'],
    			['nom' => 'Selma Benziada','daira_id' => '236'],
    			['nom' => 'El Milia','daira_id' => '237'],
    			['nom' => 'Ouled Yahia Khedrouche','daira_id' => '237'],
    			['nom' => 'Jijel','daira_id' => '238'],
    			['nom' => 'Ghebala','daira_id' => '239'],
    			['nom' => 'Settara','daira_id' => '239'],
    			['nom' => 'Ouled Rabah','daira_id' => '240'],
    			['nom' => 'Sidi Maarouf','daira_id' => '240'],
    			['nom' => 'Boucif Ouled Askeur','daira_id' => '241'],
    			['nom' => 'Chahna','daira_id' => '241'],
    			['nom' => 'Emir Abdelkader','daira_id' => '241'],
    			['nom' => 'Ouadjana','daira_id' => '241'],
    			['nom' => 'Taher','daira_id' => '241'],
    			['nom' => 'Kaous','daira_id' => '242'],
    			['nom' => 'Texenna','daira_id' => '242'],
    			['nom' => 'Eraguene','daira_id' => '243'],
    			['nom' => 'Ziama Mansouriah','daira_id' => '243'],
    			['nom' => 'Aïn Arnat','daira_id' => '244'],
    			['nom' => 'Aïn Abessa','daira_id' => '244'],
    			['nom' => 'El Ouricia','daira_id' => '244'],
    			['nom' => 'Mezloug','daira_id' => '244'],
    			['nom' => 'Aïn Azel','daira_id' => '245'],
    			['nom' => 'Aïn Lahdjar','daira_id' => '245'],
    			['nom' => 'Beidha Bordj','daira_id' => '245'],
    			['nom' => 'Bir Haddada','daira_id' => '245'],
    			['nom' => 'Aïn El Kebira','daira_id' => '246'],
    			['nom' => 'Dehamcha','daira_id' => '246'],
    			['nom' => 'Ouled Addouane','daira_id' => '246'],
    			['nom' => 'Aïn Oulmene','daira_id' => '247'],
    			['nom' => 'Guellal','daira_id' => '247'],
    			['nom' => 'Ksar El Abtal','daira_id' => '247'],
    			['nom' => 'Ouled Si Ahmed','daira_id' => '247'],
    			['nom' => 'Amoucha','daira_id' => '248'],
    			['nom' => 'Oued El Barad','daira_id' => '248'],
    			['nom' => 'Tizi N\'Bechar','daira_id' => '248'],
    			['nom' => 'Babor','daira_id' => '249'],
    			['nom' => 'Serdj El Ghoul','daira_id' => '249'],
    			['nom' => 'Beni Aziz','daira_id' => '250'],
    			['nom' => 'Aïn Sebt','daira_id' => '250'],
    			['nom' => 'Maaouia','daira_id' => '250'],
    			['nom' => 'Beni Ourtilane','daira_id' => '251'],
    			['nom' => 'Aïn Legraj','daira_id' => '251'],
    			['nom' => 'Beni Chebana','daira_id' => '251'],
    			['nom' => 'Beni Mouhli','daira_id' => '251'],
    			['nom' => 'Bir El Arch','daira_id' => '252'],
    			['nom' => 'Belaa ','daira_id' => '252'],
    			['nom' => 'El Ouldja','daira_id' => '252'],
    			['nom' => 'Tachouda','daira_id' => '252'],
    			['nom' => 'Bouandas','daira_id' => '253'],
    			['nom' => 'Aït Naoual Mezada','daira_id' => '253'],
    			['nom' => 'Aït Tizi','daira_id' => '253'],
    			['nom' => 'Bousselam','daira_id' => '253'],
    			['nom' => 'Bougaa','daira_id' => '254'],
    			['nom' => 'Aïn Roua','daira_id' => '254'],
    			['nom' => 'Beni Hocine','daira_id' => '254'],
    			['nom' => 'Djemila ','daira_id' => '255'],
    			['nom' => 'Beni Fouda','daira_id' => '255'],
    			['nom' => 'El Eulma','daira_id' => '256'],
    			['nom' => 'Bazer Sakhra','daira_id' => '256'],
    			['nom' => 'Guelta Zerka','daira_id' => '256'],
    			['nom' => 'Guidjel','daira_id' => '257'],
    			['nom' => 'Ouled Sabor','daira_id' => '257'],
    			['nom' => 'Guenzet','daira_id' => '258'],
    			['nom' => 'Harbil','daira_id' => '258'],
    			['nom' => 'Hammam Guergour','daira_id' => '259'],
    			['nom' => 'Draa Kebila','daira_id' => '259'],
    			['nom' => 'Hammam Soukhna','daira_id' => '260'],
    			['nom' => 'Taya','daira_id' => '260'],
    			['nom' => 'Tella','daira_id' => '260'],
    			['nom' => 'Maoklane','daira_id' => '261'],
    			['nom' => 'Talaifacene','daira_id' => '261'],
    			['nom' => 'Salah Bey','daira_id' => '262'],
    			['nom' => 'Boutaleb','daira_id' => '262'],
    			['nom' => 'Hamma','daira_id' => '262'],
    			['nom' => 'Ouled Tebben','daira_id' => '262'],
    			['nom' => 'Rasfa','daira_id' => '262'],
    			['nom' => 'Sétif','daira_id' => '263'],
    			['nom' => 'Saïda','daira_id' => '264'],
    			['nom' => 'Aïn El Hadjar','daira_id' => '265'],
    			['nom' => 'Moulay Larbi ','daira_id' => '265'],
    			['nom' => 'Sidi Ahmed','daira_id' => '265'],
    			['nom' => 'Sidi Boubekeur','daira_id' => '266'],
    			['nom' => 'Ouled Khaled','daira_id' => '266'],
    			['nom' => 'Sidi Amar','daira_id' => '266'],
    			['nom' => 'Hounet','daira_id' => '266'],
    			['nom' => 'El Hassasna','daira_id' => '267'],
    			['nom' => 'Aïn Sekhouna','daira_id' => '267'],
    			['nom' => 'Maamora','daira_id' => '267'],
    			['nom' => 'Ouled Brahim','daira_id' => '268'],
    			['nom' => 'Tircine','daira_id' => '268'],
    			['nom' => 'Aïn Soltane','daira_id' => '268'],
    			['nom' => 'Youb','daira_id' => '269'],
    			['nom' => 'Doui Thabet','daira_id' => '269'],
    			['nom' => 'Aïn Kechra','daira_id' => '270'],
    			['nom' => 'Ouldja Boulballout','daira_id' => '270'],
    			['nom' => 'Aïn Charchar','daira_id' => '271'],
    			['nom' => 'Azzaba','daira_id' => '271'],
    			['nom' => 'Djendel Saadi Mohamed','daira_id' => '271'],
    			['nom' => 'El Ghedir ','daira_id' => '271'],
    			['nom' => 'Es Sebt','daira_id' => '271'],
    			['nom' => 'Ben Azzouz','daira_id' => '272'],
    			['nom' => 'Bekkouche Lakhdar','daira_id' => '272'],
    			['nom' => 'El Marsa','daira_id' => '272'],
    			['nom' => 'Beni Zid','daira_id' => '273'],
    			['nom' => 'Cheraia','daira_id' => '273'],
    			['nom' => 'Collo','daira_id' => '273'],
    			['nom' => 'Aïn Zouit','daira_id' => '274'],
    			['nom' => 'Bouchtata','daira_id' => '274'],
    			['nom' => 'El Hadaiek','daira_id' => '274'],
    			['nom' => 'El Harrouch','daira_id' => '275'],
    			['nom' => 'Emdjez Edchich','daira_id' => '275'],
    			['nom' => 'Ouled Hbaba','daira_id' => '275'],
    			['nom' => 'Salah Bouchaour','daira_id' => '275'],
    			['nom' => 'Zerdaza','daira_id' => '275'],
    			['nom' => 'Kheneg Mayoum','daira_id' => '276'],
    			['nom' => 'Oued Zehour','daira_id' => '276'],
    			['nom' => 'Ouled Attia','daira_id' => '276'],
    			['nom' => 'Oum Toub','daira_id' => '277'],
    			['nom' => 'Beni Bechir','daira_id' => '278'],
    			['nom' => 'Ramdane Djamel','daira_id' => '278'],
    			['nom' => 'Aïn Bouziane','daira_id' => '279'],
    			['nom' => 'Beni Oulbane ','daira_id' => '279'],
    			['nom' => 'Sidi Mezghiche','daira_id' => '279'],
    			['nom' => 'Filfila','daira_id' => '280'],
    			['nom' => 'Hamadi Krouma','daira_id' => '280'],
    			['nom' => 'Skikda','daira_id' => '280'],
    			['nom' => 'Stora','daira_id' => '280'],
    			['nom' => 'Bin El Ouiden','daira_id' => '281'],
    			['nom' => 'Kerkera','daira_id' => '281'],
    			['nom' => 'Tamalous','daira_id' => '281'],
    			['nom' => 'Kanoua','daira_id' => '282'],
    			['nom' => 'Zitouna','daira_id' => '282'],
    			['nom' => 'Sidi Bel Abbès','daira_id' => '283'],
          ['nom' => 'Ain El Berd','daira_id' => '284'],
          ['nom' => 'Sidi Brahim','daira_id' => '284'],
          ['nom' => 'Makedra','daira_id' => '284'],
          ['nom' => 'Sidi Hamadouche','daira_id' => '284'],
          ['nom' => 'Ben Badis','daira_id' => '285'],
          ['nom' => 'Badredine El Mokrani','daira_id' => '285'],
          ['nom' => 'Hassi Zahana','daira_id' => '285'],
          ['nom' => 'Chettouane Belaila','daira_id' => '285'],
          ['nom' => 'Marhoum','daira_id' => '286'],
          ['nom' => 'Sidi Chaib ','daira_id' => '286'],
          ['nom' => 'Bir El Hammam','daira_id' => '286'],
          ['nom' => 'Merine','daira_id' => '287'],
          ['nom' => 'Tafissour','daira_id' => '287'],
          ['nom' => 'Oued Taourira','daira_id' => '287'],
          ['nom' => 'Taoudmout','daira_id' => '287'],
          ['nom' => 'Mostefa Ben Brahim','daira_id' => '288'],
          ['nom' => 'Tilmouni','daira_id' => '288'],
          ['nom' => 'Zerouala','daira_id' => '288'],
          ['nom' => 'Belarbi','daira_id' => '288'],
          ['nom' => 'Moulay Slissen','daira_id' => '289'],
          ['nom' => 'El Haçaiba','daira_id' => '289'],
          ['nom' => 'Aïn Tindamine','daira_id' => '289'],
          ['nom' => 'Ras El Ma','daira_id' => '290'],
          ['nom' => 'Oued Sebaa','daira_id' => '290'],
          ['nom' => 'Redjem Demouche','daira_id' => '290'],
          ['nom' => 'Sfisef','daira_id' => '291'],
          ['nom' => 'M\'Cid','daira_id' => '291'],
          ['nom' => 'Aïn Adden','daira_id' => '291'],
          ['nom' => 'Boudjebaa El Bordj','daira_id' => '291'],
          ['nom' => 'Sidi Ali Benyoub','daira_id' => '292'],
          ['nom' => 'Boukhanafis','daira_id' => '292'],
          ['nom' => 'Tabia','daira_id' => '292'],
          ['nom' => 'Sidi Ali Boussidi','daira_id' => '293'],
          ['nom' => 'Aïn Kada','daira_id' => '293'],
          ['nom' => 'Lamtar','daira_id' => '293'],
          ['nom' => 'Sidi Daho des Zairs','daira_id' => '293'],
          ['nom' => 'Sidi Lahcene','daira_id' => '294'],
          ['nom' => 'Amarnas','daira_id' => '294'],
          ['nom' => 'Sidi Khaled','daira_id' => '294'],
          ['nom' => 'Sidi Yacoub','daira_id' => '294'],
          ['nom' => 'Telagh','daira_id' => '295'],
          ['nom' => 'Mezaourou','daira_id' => '295'],
          ['nom' => 'Dhaya ','daira_id' => '295'],
          ['nom' => 'Teghalimet','daira_id' => '295'],
          ['nom' => 'Tenira','daira_id' => '296'],
          ['nom' => 'Oued Sefioun','daira_id' => '296'],
          ['nom' => 'Benachiba Chelia','daira_id' => '296'],
          ['nom' => 'Hassi Dahou','daira_id' => '296'],
          ['nom' => 'Tessala','daira_id' => '297'],
          ['nom' => 'Ain Thrid','daira_id' => '297'],
          ['nom' => 'Sehala Thaoura','daira_id' => '297'],
          ['nom' => 'Annaba','daira_id' => '298'],
          ['nom' => 'Seraïdi','daira_id' => '298'],
          ['nom' => 'Aïn Berda','daira_id' => '299'],
          ['nom' => 'Cheurfa','daira_id' => '299'],
          ['nom' => 'Eulma','daira_id' => '299'],
          ['nom' => 'El Hadjar','daira_id' => '300'],
          ['nom' => 'Sidi Amar','daira_id' => '300'],
          ['nom' => 'Berrahal','daira_id' => '301'],
          ['nom' => 'Oued El Aneb','daira_id' => '301'],
          ['nom' => 'Treat','daira_id' => '301'],
          ['nom' => 'Chetaïbi','daira_id' => '302'],
          ['nom' => 'El Bouni','daira_id' => '303'],
          ['nom' => 'BENDJARAH','daira_id' => '304'],
          ['nom' => 'GUELMA','daira_id' => '304'],
          ['nom' => 'HOUARI BOUMEDIENNE','daira_id' => '313'],
          ['nom' => 'MEDJEZ AMAR','daira_id' => '313'],
          ['nom' => 'RAS EL AGBA','daira_id' => '313'],
          ['nom' => 'SELLAOUA ANNOUNA','daira_id' => '313'],
          ['nom' => 'BOUATI MAHMOUD','daira_id' => '307'],
          ['nom' => 'EL FEDJOUDJ','daira_id' => '307'],
          ['nom' => 'HELIOPOLIS','daira_id' => '307'],
          ['nom' => 'AIN HESSAINIA','daira_id' => '313'],
          ['nom' => 'AIN BEN BEIDA','daira_id' => '311'],
          ['nom' => 'BOUCHEGOUF','daira_id' => '311'],
          ['nom' => 'MEDJEZ SFA','daira_id' => '311'],
          ['nom' => 'OUED FERRAGHA','daira_id' => '311'],
          ['nom' => 'DAHOUARA','daira_id' => '312'],
          ['nom' => 'HAMMAM N\'BAIL','daira_id' => '312'],
          ['nom' => 'OUED CHEHAM','daira_id' => '312'],
          ['nom' => 'BOU HAMDANE','daira_id' => '310'],
          ['nom' => 'HAMMAM DEBAGH','daira_id' => '310'],
          ['nom' => 'ROKNIA','daira_id' => '310'],
          ['nom' => 'BELKHEIR','daira_id' => '306'],
          ['nom' => 'BENI MEZLINE','daira_id' => '306'],
          ['nom' => 'BOUMAHRA AHMED','daira_id' => '306'],
          ['nom' => 'DJEBALLAH KHEMISSI','daira_id' => '306'],
          ['nom' => 'GUELAAT BOU SBAA','daira_id' => '306'],
          ['nom' => 'NECHMAYA','daira_id' => '306'],
          ['nom' => 'AIN SANDEL','daira_id' => '305'],
          ['nom' => 'BOU HACHANA','daira_id' => '305'],
          ['nom' => 'KHEZARAS','daira_id' => '305'],
          ['nom' => 'AIN LARBI','daira_id' => '309'],
          ['nom' => 'AIN MAKHLOUF','daira_id' => '309'],
          ['nom' => 'TAMLOUKA','daira_id' => '309'],
          ['nom' => 'AIN REGADA','daira_id' => '308'],
          ['nom' => 'BORDJ SABATH','daira_id' => '308'],
          ['nom' => 'OUED ZENATI','daira_id' => '308'],
          ['nom' => 'Constantine','daira_id' => '315'],
          ['nom' => 'El Khroub','daira_id' => '316'],
          ['nom' => 'Aïn Smara','daira_id' => '316'],
          ['nom' => 'Ouled Rahmoune','daira_id' => '316'],
          ['nom' => 'Ali Mendjeli','daira_id' => '316'],
          ['nom' => 'Aïn Abid','daira_id' => '317'],
          ['nom' => 'Ibn Badis','daira_id' => '317'],
          ['nom' => 'Zighoud Youcef','daira_id' => '318'],
          ['nom' => 'Beni Hamiden','daira_id' => '318'],
          ['nom' => 'Hamma Bouziane','daira_id' => '319'],
          ['nom' => 'Didouche Mourad','daira_id' => '319'],
          ['nom' => 'Ibn Ziad','daira_id' => '320'],
          ['nom' => 'Messaoud Boudjriou','daira_id' => '320'],
          ['nom' => 'Aïn Boucif','daira_id' => '321'],
          ['nom' => 'Kef Lakhdar','daira_id' => '321'],
          ['nom' => 'Ouled Maaref','daira_id' => '321'],
          ['nom' => 'Sidi Damed','daira_id' => '321'],
          ['nom' => 'El Ouinet','daira_id' => '321'],
          ['nom' => 'Aziz','daira_id' => '322'],
          ['nom' => 'Oum El Djalil','daira_id' => '322'],
          ['nom' => 'Derrag','daira_id' => '322'],
          ['nom' => 'Beni Slimane','daira_id' => '323'],
          ['nom' => 'Sidi Errabia','daira_id' => '323'],
          ['nom' => 'Bouskene','daira_id' => '323'],
          ['nom' => 'Berrouaghia','daira_id' => '324'],
          ['nom' => 'Rebaia','daira_id' => '324'],
          ['nom' => 'Ouled Deide','daira_id' => '324'],
          ['nom' => 'Chahbounia','daira_id' => '325'],
          ['nom' => 'Boughezoul','daira_id' => '325'],
          ['nom' => 'Bou Aiche','daira_id' => '325'],
          ['nom' => 'Chellalet El Adhaoura','daira_id' => '326'],
          ['nom' => 'Cheniguel','daira_id' => '326'],
          ['nom' => 'Tafraout','daira_id' => '326'],
          ['nom' => 'Aïn Ouksir','daira_id' => '326'],
          ['nom' => 'El Azizia','daira_id' => '327'],
          ['nom' => 'Meghraoua','daira_id' => '327'],
          ['nom' => 'Mihoub','daira_id' => '327'],
          ['nom' => 'El Guelb El Kebir','daira_id' => '328'],
          ['nom' => 'Sedraia','daira_id' => '328'],
          ['nom' => 'Bir Ben Laabed','daira_id' => '328'],
          ['nom' => 'El Omaria','daira_id' => '329'],
          ['nom' => 'Baata','daira_id' => '329'],
          ['nom' => 'Ouled Brahim','daira_id' => '329'],
          ['nom' => 'Ksar Boukhari','daira_id' => '330'],
          ['nom' => 'Meftaha','daira_id' => '330'],
          ['nom' => 'Saneg','daira_id' => '330'],
          ['nom' => 'Médéa','daira_id' => '331'],
          ['nom' => 'Draa Essamar','daira_id' => '331'],
          ['nom' => 'Tamesguida','daira_id' => '331'],
          ['nom' => 'Ouamri','daira_id' => '332'],
          ['nom' => 'Oued Harbil','daira_id' => '332'],
          ['nom' => 'Hannacha','daira_id' => '332'],
          ['nom' => 'Ouled Antar','daira_id' => '333'],
          ['nom' => 'Boghar','daira_id' => '333'],
          ['nom' => 'Ouled Hellal','daira_id' => '333'],
          ['nom' => 'Ouzera','daira_id' => '334'],
          ['nom' => 'Tizi Mahdi','daira_id' => '334'],
          ['nom' => 'El Hamdania','daira_id' => '334'],
          ['nom' => 'Benchicao','daira_id' => '334'],
          ['nom' => 'Seghouane','daira_id' => '335'],
          ['nom' => 'Zoubiria','daira_id' => '335'],
          ['nom' => 'Moudjbar','daira_id' => '335'],
          ['nom' => 'Tlatet Eddouar','daira_id' => '335'],
          ['nom' => 'Sidi Naamane','daira_id' => '336'],
          ['nom' => 'Khams Djouamaa','daira_id' => '336'],
          ['nom' => 'Bouchrahil','daira_id' => '336'],
          ['nom' => 'Si Mahdjoub','daira_id' => '337'],
          ['nom' => 'Ouled Bouachra','daira_id' => '337'],
          ['nom' => 'Bouaichoune','daira_id' => '337'],
          ['nom' => 'Souagui','daira_id' => '338'],
          ['nom' => 'Djouab','daira_id' => '338'],
          ['nom' => 'Sidi Zahar','daira_id' => '338'],
          ['nom' => 'Sidi Ziane','daira_id' => '338'],
          ['nom' => 'Tablat','daira_id' => '339'],
          ['nom' => 'Deux Bassins','daira_id' => '339'],
          ['nom' => 'Aissaouia','daira_id' => '339'],
          ['nom' => 'Mezerana','daira_id' => '339'],
          ['nom' => 'Mostaganem','daira_id' => '340'],
          ['nom' => 'Hassi Mameche','daira_id' => '341'],
          ['nom' => 'Mazagran','daira_id' => '341'],
          ['nom' => 'Stidia','daira_id' => '341'],
          ['nom' => 'Ain Tedles','daira_id' => '342'],
          ['nom' => 'Sour','daira_id' => '342'],
          ['nom' => 'Sidi Belattar','daira_id' => '342'],
          ['nom' => 'Oued El Kheir','daira_id' => '342'],
          ['nom' => 'Bouguirat','daira_id' => '343'],
          ['nom' => 'Safsaf','daira_id' => '343'],
          ['nom' => 'Sirat','daira_id' => '343'],
          ['nom' => 'Souaflia','daira_id' => '343'],
          ['nom' => 'Sidi Ali','daira_id' => '344'],
          ['nom' => 'Ouled Maallah','daira_id' => '344'],
          ['nom' => 'Tazgait','daira_id' => '344'],
          ['nom' => 'Achaacha','daira_id' => '345'],
          ['nom' => 'Khadra','daira_id' => '345'],
          ['nom' => 'Nekmaria','daira_id' => '345'],
          ['nom' => 'Ouled Boughalem','daira_id' => '345'],
          ['nom' => 'Aïn Nouïssy','daira_id' => '346'],
          ['nom' => 'El Hassaine','daira_id' => '346'],
          ['nom' => 'Fornaka','daira_id' => '346'],
          ['nom' => 'Mesra','daira_id' => '347'],
          ['nom' => 'Aïn Sidi Cherif','daira_id' => '347'],
          ['nom' => 'Mansourah','daira_id' => '347'],
          ['nom' => 'Blad Touahria','daira_id' => '347'],
          ['nom' => 'Sidi Lakhdar','daira_id' => '348'],
          ['nom' => 'Hadjadj','daira_id' => '348'],
          ['nom' => 'Abdelmalek Ramdane','daira_id' => '348'],
          ['nom' => 'Kheireddine','daira_id' => '349'],
          ['nom' => 'Ain Boudinar','daira_id' => '349'],
          ['nom' => 'Sayada','daira_id' => '349'],
          ['nom' => 'M\'Sila','daira_id' => '350'],
          ['nom' => 'Hammam Dalaa','daira_id' => '351'],
          ['nom' => 'Tarmount','daira_id' => '351'],
          ['nom' => 'Ouled Mansour','daira_id' => '351'],
          ['nom' => 'Ouanougha','daira_id' => '351'],
          ['nom' => 'Ouled Derradj','daira_id' => '352'],
          ['nom' => 'Maadid','daira_id' => '352'],
          ['nom' => 'M\'Tarfa','daira_id' => '352'],
          ['nom' => 'Ouled Addi Guebala','daira_id' => '352'],
          ['nom' => 'Souamaa','daira_id' => '352'],
          ['nom' => 'Sidi Aissa','daira_id' => '353'],
          ['nom' => 'Bouti Sayah','daira_id' => '353'],
          ['nom' => 'Beni Ilmane','daira_id' => '353'],
          ['nom' => 'Aïn El Melh','daira_id' => '354'],
          ['nom' => 'Bir Foda','daira_id' => '354'],
          ['nom' => 'Aïn Fares','daira_id' => '354'],
          ['nom' => 'Sidi M\'hamed','daira_id' => '354'],
          ['nom' => 'Aïn Errich','daira_id' => '354'],
          ['nom' => 'Ben Srour','daira_id' => '355'],
          ['nom' => 'Ouled Slimane','daira_id' => '355'],
          ['nom' => 'Zarzour','daira_id' => '355'],
          ['nom' => 'Mohammed Boudiaf','daira_id' => '355'],
          ['nom' => 'Bou Saada','daira_id' => '356'],
          ['nom' => 'El Hamel','daira_id' => '356'],
          ['nom' => 'Oultem','daira_id' => '356'],
          ['nom' => 'Ouled Sidi Brahim','daira_id' => '357'],
          ['nom' => 'Benzouh','daira_id' => '357'],
          ['nom' => 'Sidi Ameur','daira_id' => '358'],
          ['nom' => 'Tamsa','daira_id' => '358'],
          ['nom' => 'Magra','daira_id' => '359'],
          ['nom' => 'Berhoum','daira_id' => '359'],
          ['nom' => 'Aïn El Khadra','daira_id' => '359'],
          ['nom' => 'Belaiba','daira_id' => '359'],
          ['nom' => 'Dehahna','daira_id' => '359'],
          ['nom' => 'Chellal','daira_id' => '360'],
          ['nom' => 'Ouled Madhi','daira_id' => '360'],
          ['nom' => 'Khettouti Sed El Djir','daira_id' => '360'],
          ['nom' => 'Maarif','daira_id' => '360'],
          ['nom' => 'Khoubana','daira_id' => '361'],
          ['nom' => 'M\'Cif','daira_id' => '361'],
          ['nom' => 'El Houamed','daira_id' => '361'],
          ['nom' => 'Medjedel','daira_id' => '362'],
          ['nom' => 'Ouled Atia','daira_id' => '362'],
          ['nom' => 'Aïn El Hadjel','daira_id' => '363'],
          ['nom' => 'Sidi Hadjeres','daira_id' => '363'],
          ['nom' => 'Djebel Messaad','daira_id' => '364'],
          ['nom' => 'Slim','daira_id' => '364'],
          ['nom' => 'Aïn Fares','daira_id' => '365'],
          ['nom' => 'Mamounia','daira_id' => '365'],
          ['nom' => 'Aïn Fekan','daira_id' => '366'],
          ['nom' => 'Aïn Fras','daira_id' => '366'],
          ['nom' => 'Aouf','daira_id' => '367'],
          ['nom' => 'Gharrous','daira_id' => '367'],
          ['nom' => 'Beniane','daira_id' => '367'],
          ['nom' => 'Bou Hanifia','daira_id' => '368'],
          ['nom' => 'El Guettana','daira_id' => '368'],
          ['nom' => 'Hacine','daira_id' => '368'],
          ['nom' => 'El Bordj','daira_id' => '369'],
          ['nom' => 'Khalouia','daira_id' => '369'],
          ['nom' => 'El Menaouer','daira_id' => '369'],
          ['nom' => 'Ghriss','daira_id' => '370'],
          ['nom' => 'Makdha','daira_id' => '370'],
          ['nom' => 'Matemore','daira_id' => '370'],
          ['nom' => 'Sidi Boussaid','daira_id' => '370'],
          ['nom' => 'Maoussa','daira_id' => '370'],
          ['nom' => 'Hachem','daira_id' => '371'],
          ['nom' => 'Zelmata','daira_id' => '371'],
          ['nom' => 'Nesmoth','daira_id' => '371'],
          ['nom' => 'Mascara','daira_id' => '372'],
          ['nom' => 'Mohammadia','daira_id' => '373'],
          ['nom' => 'El Ghomri','daira_id' => '373'],
          ['nom' => 'Ferraguig','daira_id' => '373'],
          ['nom' => 'Mocta Douz','daira_id' => '373'],
          ['nom' => 'Sedjerara','daira_id' => '373'],
          ['nom' => 'Sidi Abdelmoumen','daira_id' => '373'],
          ['nom' => 'Oggaz','daira_id' => '374'],
          ['nom' => 'Alaïmia','daira_id' => '374'],
          ['nom' => 'Ras El Aïn Amirouche','daira_id' => '374'],
          ['nom' => 'Oued El Abtal','daira_id' => '375'],
          ['nom' => 'Aïn Ferah','daira_id' => '375'],
          ['nom' => 'Sidi Abdeldjebar','daira_id' => '375'],
          ['nom' => 'Oued Taria','daira_id' => '376'],
          ['nom' => 'Guerdjoum','daira_id' => '376'],
          ['nom' => 'Sig','daira_id' => '377'],
          ['nom' => 'Chorfa','daira_id' => '377'],
          ['nom' => 'Bou Henni','daira_id' => '377'],
          ['nom' => 'Tighennif','daira_id' => '378'],
          ['nom' => 'Sidi Kada','daira_id' => '378'],
          ['nom' => 'Sehailia','daira_id' => '378'],
          ['nom' => 'Tizi','daira_id' => '379'],
          ['nom' => 'Froha','daira_id' => '379'],
          ['nom' => 'El Keurt','daira_id' => '379'],
          ['nom' => 'El Gaada','daira_id' => '380'],
          ['nom' => 'Zahana','daira_id' => '380'],
          ['nom' => 'El Borma','daira_id' => '381'],
          ['nom' => 'El Hadjira','daira_id' => '382'],
          ['nom' => 'El Allia','daira_id' => '382'],
          ['nom' => 'Hassi Messaoud','daira_id' => '383'],
          ['nom' => 'Megarine','daira_id' => '384'],
          ['nom' => 'Sidi Slimane','daira_id' => '384'],
          ['nom' => 'N\'Goussa','daira_id' => '385'],
          ['nom' => 'Ouargla','daira_id' => '386'],
          ['nom' => 'Rouissat','daira_id' => '386'],
          ['nom' => 'Aïn Beida','daira_id' => '387'],
          ['nom' => 'Hassi Ben Abdellah','daira_id' => '387'],
          ['nom' => 'Sidi Khouiled','daira_id' => '387'],
          ['nom' => 'Benaceur','daira_id' => '388'],
          ['nom' => 'M\'Naguer','daira_id' => '388'],
          ['nom' => 'Taibet','daira_id' => '388'],
          ['nom' => 'Blidet Amor','daira_id' => '389'],
          ['nom' => 'Tamacine','daira_id' => '389'],
          ['nom' => 'Nezla','daira_id' => '390'],
          ['nom' => 'Tebesbest','daira_id' => '390'],
          ['nom' => 'Touggourt','daira_id' => '390'],
          ['nom' => 'Zaouia El Abidia','daira_id' => '390'],
          ['nom' => 'Oran','daira_id' => '392'],
          ['nom' => 'Aïn El Turk','daira_id' => '393'],
          ['nom' => 'Bousfer','daira_id' => '393'],
          ['nom' => 'El Ançor','daira_id' => '393'],
          ['nom' => 'Mers El Kébir','daira_id' => '393'],
          ['nom' => 'Arzew','daira_id' => '394'],
          ['nom' => 'Sidi Benyebka','daira_id' => '394'],
          ['nom' => 'Aïn El Bia','daira_id' => '395'],
          ['nom' => 'Bethioua','daira_id' => '395'],
          ['nom' => 'Marsat El Hadjadj','daira_id' => '395'],
          ['nom' => 'El Kerma','daira_id' => '396'],
          ['nom' => 'Es Senia','daira_id' => '396'],
          ['nom' => 'Sidi Chami','daira_id' => '396'],
          ['nom' => 'Bir El Djir','daira_id' => '397'],
          ['nom' => 'Hassi Ben Okba','daira_id' => '397'],
          ['nom' => 'Hassi Bounif','daira_id' => '397'],
          ['nom' => 'Aïn El Kerma','daira_id' => '398'],
          ['nom' => 'Boutlélis','daira_id' => '398'],
          ['nom' => 'Misserghin','daira_id' => '398'],
          ['nom' => 'Boufatis','daira_id' => '399'],
          ['nom' => 'El Braya','daira_id' => '399'],
          ['nom' => 'Oued Tlelat','daira_id' => '399'],
          ['nom' => 'Tafraoui','daira_id' => '399'],
          ['nom' => 'Ben Freha','daira_id' => '400'],
          ['nom' => 'Gdyel','daira_id' => '400'],
          ['nom' => 'Hassi Mefsoukh','daira_id' => '400'],
          ['nom' => 'El Bayadh','daira_id' => '401'],
          ['nom' => 'Cheguig','daira_id' => '402'],
          ['nom' => 'Kef El Ahmar','daira_id' => '402'],
          ['nom' => 'Rogassa','daira_id' => '402'],
          ['nom' => 'Brezina','daira_id' => '403'],
          ['nom' => 'Kraakda','daira_id' => '403'],
          ['nom' => 'Ghassoul','daira_id' => '403'],
          ['nom' => 'Aïn El Orak','daira_id' => '404'],
          ['nom' => 'Arbaouat','daira_id' => '404'],
          ['nom' => 'El Abiodh Sidi Cheikh','daira_id' => '404'],
          ['nom' => 'El Bnoud','daira_id' => '404'],
          ['nom' => 'Bougtoub','daira_id' => '405'],
          ['nom' => 'El Kheiter','daira_id' => '405'],
          ['nom' => 'Tousmouline','daira_id' => '405'],
          ['nom' => 'Chellala','daira_id' => '406'],
          ['nom' => 'El Mehara','daira_id' => '406'],
          ['nom' => 'Boussemghoun','daira_id' => '407'],
          ['nom' => 'Boualem','daira_id' => '408'],
          ['nom' => 'Sidi Ameur','daira_id' => '408'],
          ['nom' => 'Sidi Slimane','daira_id' => '408'],
          ['nom' => 'Sidi Tifour','daira_id' => '408'],
          ['nom' => 'Stitten','daira_id' => '408'],
          ['nom' => 'Illizi','daira_id' => '409'],
          ['nom' => 'Djanet','daira_id' => '410'],
          ['nom' => 'Bordj El Haouas','daira_id' => '410'],
          ['nom' => 'In Amenas','daira_id' => '411'],
          ['nom' => 'Bordj Omar Driss','daira_id' => '411'],
          ['nom' => 'Debdeb','daira_id' => '411'],
          ['nom' => 'Bordj Bou Arreridj','daira_id' => '412'],
          ['nom' => 'Aïn Taghrout','daira_id' => '413'],
          ['nom' => 'Tixter','daira_id' => '413'],
          ['nom' => 'Aïn Tesra','daira_id' => '414'],
          ['nom' => 'Ras El Oued','daira_id' => '414'],
          ['nom' => 'Ouled Brahim','daira_id' => '414'],
          ['nom' => 'Belimour','daira_id' => '415'],
          ['nom' => 'Bordj Ghedir','daira_id' => '415'],
          ['nom' => 'El Anceur','daira_id' => '415'],
          ['nom' => 'Ghilassa','daira_id' => '415'],
          ['nom' => 'Taglait','daira_id' => '415'],
          ['nom' => 'Bir Kasdali','daira_id' => '416'],
          ['nom' => 'Khelil','daira_id' => '416'],
          ['nom' => 'Sidi Embarek','daira_id' => '416'],
          ['nom' => 'El Ach','daira_id' => '417'],
          ['nom' => 'El Hamadia','daira_id' => '417'],
          ['nom' => 'Ksour','daira_id' => '417'],
          ['nom' => 'Rabta','daira_id' => '417'],
          ['nom' => 'Ben Daoud','daira_id' => '418'],
          ['nom' => 'El M\'hir','daira_id' => '418'],
          ['nom' => 'Haraza','daira_id' => '418'],
          ['nom' => 'Mansoura','daira_id' => '418'],
          ['nom' => 'Ouled Sidi Brahim','daira_id' => '418'],
          ['nom' => 'El Achir','daira_id' => '419'],
          ['nom' => 'Hasnaoua','daira_id' => '419'],
          ['nom' => 'Medjana','daira_id' => '419'],
          ['nom' => 'Teniet En Nasr','daira_id' => '419'],
          ['nom' => 'Bordj Zemoura','daira_id' => '420'],
          ['nom' => 'Ouled Dahmane','daira_id' => '420'],
          ['nom' => 'Tassameurt','daira_id' => '420'],
          ['nom' => 'Colla','daira_id' => '421'],
          ['nom' => 'Djaafra','daira_id' => '421'],
          ['nom' => 'El Main','daira_id' => '421'],
          ['nom' => 'Tefreg','daira_id' => '421'],
          ['nom' => 'Baghlia','daira_id' => '422'],
          ['nom' => 'Sidi Daoud','daira_id' => '422'],
          ['nom' => 'Taourga','daira_id' => '422'],
          ['nom' => 'Bordj Ménaïel','daira_id' => '423'],
          ['nom' => 'Zemmouri','daira_id' => '423'],
          ['nom' => 'Leghata','daira_id' => '423'],
          ['nom' => 'Djinet','daira_id' => '423'],
          ['nom' => 'Boudouaou','daira_id' => '424'],
          ['nom' => 'Boudouaou El Bahri','daira_id' => '424'],
          ['nom' => 'El Kharrouba','daira_id' => '424'],
          ['nom' => 'Bouzegza Keddara','daira_id' => '424'],
          ['nom' => 'Ouled Hedadj','daira_id' => '424'],
          ['nom' => 'Boumerdès','daira_id' => '425'],
          ['nom' => 'Corso','daira_id' => '425'],
          ['nom' => 'Tidjelabine','daira_id' => '425'],
          ['nom' => 'Dellys','daira_id' => '426'],
          ['nom' => 'Afir','daira_id' => '426'],
          ['nom' => 'Ben Choud','daira_id' => '426'],
          ['nom' => 'Issers','daira_id' => '427'],
          ['nom' => 'Si Mustapha','daira_id' => '427'],
          ['nom' => 'Timezrit','daira_id' => '427'],
          ['nom' => 'Chabet El Ameur','daira_id' => '427'],
          ['nom' => 'Khemis El Khechna','daira_id' => '428'],
          ['nom' => 'Ouled Moussa','daira_id' => '428'],
          ['nom' => 'Larbatache','daira_id' => '428'],
          ['nom' => 'Hammadi','daira_id' => '428'],
          ['nom' => 'Naciria','daira_id' => '429'],
          ['nom' => 'Ouled Aïssa','daira_id' => '429'],
          ['nom' => 'Thénia','daira_id' => '430'],
          ['nom' => 'Souk El Had','daira_id' => '430'],
          ['nom' => 'Béni Amrane','daira_id' => '430'],
          ['nom' => 'Ammal','daira_id' => '430'],
          ['nom' => 'El Tarf','daira_id' => '431'],
          ['nom' => 'Aïn El Assel','daira_id' => '431'],
          ['nom' => 'Bougous','daira_id' => '431'],
          ['nom' => 'Zitouna','daira_id' => '431'],
          ['nom' => 'El Kala','daira_id' => '432'],
          ['nom' => 'Souarekh','daira_id' => '432'],
          ['nom' => 'Raml Souk','daira_id' => '432'],
          ['nom' => 'El Aioun','daira_id' => '432'],
          ['nom' => 'Ben Mehidi','daira_id' => '433'],
          ['nom' => 'Echatt','daira_id' => '433'],
          ['nom' => 'Berrihane','daira_id' => '433'],
          ['nom' => 'Besbes','daira_id' => '434'],
          ['nom' => 'Asfour','daira_id' => '434'],
          ['nom' => 'Zerizer','daira_id' => '434'],
          ['nom' => 'Dréan','daira_id' => '435'],
          ['nom' => 'Chebaita Mokhtar','daira_id' => '435'],
          ['nom' => 'Chihani','daira_id' => '435'],
          ['nom' => 'Bouhadjar','daira_id' => '436'],
          ['nom' => 'Aïn Kerma','daira_id' => '436'],
          ['nom' => 'Oued Zitoun','daira_id' => '436'],
          ['nom' => 'Hammam Beni Salah','daira_id' => '436'],
          ['nom' => 'Bouteldja','daira_id' => '437'],
          ['nom' => 'Lac des Oiseaux','daira_id' => '437'],
          ['nom' => 'Chefia','daira_id' => '437'],
          ['nom' => 'Tindouf','daira_id' => '438'],
          ['nom' => 'Oum el Assel','daira_id' => '438'],
          ['nom' => 'Ammari','daira_id' => '439'],
          ['nom' => 'Maacem','daira_id' => '439'],
          ['nom' => 'Sidi Abed','daira_id' => '439'],
          ['nom' => 'Bordj Bou Naama','daira_id' => '440'],
          ['nom' => 'Beni Chaib','daira_id' => '440'],
          ['nom' => 'Beni Lahcene','daira_id' => '440'],
          ['nom' => 'Sidi Slimane','daira_id' => '440'],
          ['nom' => 'Bordj El Emir Abdelkader','daira_id' => '441'],
          ['nom' => 'Youssoufia','daira_id' => '441'],
          ['nom' => 'Khemisti','daira_id' => '442'],
          ['nom' => 'Layoune','daira_id' => '442'],
          ['nom' => 'Lardjem','daira_id' => '443'],
          ['nom' => 'Melaab','daira_id' => '443'],
          ['nom' => 'Sidi Lantri','daira_id' => '443'],
          ['nom' => 'Tamalaht','daira_id' => '443'],
          ['nom' => 'Lazharia','daira_id' => '444'],
          ['nom' => 'Boucaid','daira_id' => '444'],
          ['nom' => 'Larbaâ','daira_id' => '444'],
          ['nom' => 'Theniet El Had','daira_id' => '445'],
          ['nom' => 'Sidi Boutouchent','daira_id' => '445'],
          ['nom' => 'Tissemsilt','daira_id' => '446'],
          ['nom' => 'Ouled Bessem','daira_id' => '446'],
          ['nom' => 'Bayadha','daira_id' => '447'],
          ['nom' => 'Debila','daira_id' => '448'],
          ['nom' => 'Hassani Abdelkrim','daira_id' => '448'],
          ['nom' => 'Djamaa','daira_id' => '449'],
          ['nom' => 'M\'Rara','daira_id' => '449'],
          ['nom' => 'Sidi Amrane','daira_id' => '449'],
          ['nom' => 'Tendla','daira_id' => '449'],
          ['nom' => 'El M\'Ghair','daira_id' => '450'],
          ['nom' => 'Oum Touyour','daira_id' => '450'],
          ['nom' => 'Sidi Khellil','daira_id' => '450'],
          ['nom' => 'Still','daira_id' => '450'],
          ['nom' => 'El Oued','daira_id' => '451'],
          ['nom' => 'Kouinine','daira_id' => '451'],
          ['nom' => 'Guemar','daira_id' => '452'],
          ['nom' => 'Ourmas','daira_id' => '452'],
          ['nom' => 'Taghzout','daira_id' => '452'],
          ['nom' => 'Hassi Khalifa','daira_id' => '453'],
          ['nom' => 'Trifaoui','daira_id' => '453'],
          ['nom' => 'Magrane','daira_id' => '454'],
          ['nom' => 'Sidi Aoun','daira_id' => '454'],
          ['nom' => 'Mih Ouansa','daira_id' => '455'],
          ['nom' => 'Oued El Alenda','daira_id' => '455'],
          ['nom' => 'Hamraia','daira_id' => '456'],
          ['nom' => 'Reguiba','daira_id' => '456'],
          ['nom' => 'Nakhla','daira_id' => '457'],
          ['nom' => 'Robbah','daira_id' => '457'],
          ['nom' => 'El Ogla','daira_id' => '457'],
          ['nom' => 'Beni Guecha','daira_id' => '458'],
          ['nom' => 'Douar El Ma','daira_id' => '458'],
          ['nom' => 'Taleb Larbi','daira_id' => '458'],
          ['nom' => 'Khenchela','daira_id' => '459'],
          ['nom' => 'Babar','daira_id' => '460'],
          ['nom' => 'Bouhmama','daira_id' => '461'],
          ['nom' => 'Chélia','daira_id' => '461'],
          ['nom' => 'M\'Sara','daira_id' => '461'],
          ['nom' => 'Yabous','daira_id' => '461'],
          ['nom' => 'Chechar','daira_id' => '462'],
          ['nom' => 'Djellal','daira_id' => '462'],
          ['nom' => 'El Oueldja','daira_id' => '462'],
          ['nom' => 'Khirane','daira_id' => '462'],
          ['nom' => 'Baghaï','daira_id' => '463'],
          ['nom' => 'El Hamma','daira_id' => '463'],
          ['nom' => 'Ensigha','daira_id' => '463'],
          ['nom' => 'Tamza','daira_id' => '463'],
          ['nom' => 'Kais','daira_id' => '464'],
          ['nom' => 'Remila','daira_id' => '464'],
          ['nom' => 'Taouzient','daira_id' => '464'],
          ['nom' => 'El Mahmal','daira_id' => '465'],
          ['nom' => 'Ouled Rechache','daira_id' => '465'],
          ['nom' => 'Aïn Touila','daira_id' => '466'],
          ['nom' => 'M\'Toussa','daira_id' => '466'],
          ['nom' => 'Bir Bou Haouch','daira_id' => '467'],
          ['nom' => 'Zouabi','daira_id' => '467'],
          ['nom' => 'Safel El Ouiden','daira_id' => '467'],
          ['nom' => 'Heddada','daira_id' => '468'],
          ['nom' => 'Khedara','daira_id' => '468'],
          ['nom' => 'Ouled Moumen','daira_id' => '468'],
          ['nom' => 'M\'daourouch','daira_id' => '469'],
          ['nom' => 'Tiffech','daira_id' => '469'],
          ['nom' => 'Ragouba','daira_id' => '469'],
          ['nom' => 'Mechroha','daira_id' => '470'],
          ['nom' => 'Hanancha','daira_id' => '470'],
          ['nom' => 'Merahna','daira_id' => '471'],
          ['nom' => 'Ouillen','daira_id' => '471'],
          ['nom' => 'Sidi Fredj','daira_id' => '471'],
          ['nom' => 'Ouled Driss','daira_id' => '472'],
          ['nom' => 'Aïn Zana','daira_id' => '472'],
          ['nom' => 'Oum El Adhaim','daira_id' => '473'],
          ['nom' => 'Terraguelt','daira_id' => '473'],
          ['nom' => 'Oued Keberit','daira_id' => '473'],
          ['nom' => 'Sedrata','daira_id' => '474'],
          ['nom' => 'Khemissa','daira_id' => '474'],
          ['nom' => 'Aïn Soltane','daira_id' => '474'],
          ['nom' => 'Souk Ahras','daira_id' => '475'],
          ['nom' => 'Taoura','daira_id' => '476'],
          ['nom' => 'Dréa','daira_id' => '476'],
          ['nom' => 'Zaarouria','daira_id' => '476'],
          ['nom' => 'Ahmar El Ain','daira_id' => '477'],
          ['nom' => 'Bourkika','daira_id' => '477'],
          ['nom' => 'Sidi Rached','daira_id' => '477'],
          ['nom' => 'Bou Ismail','daira_id' => '478'],
          ['nom' => 'Ain Tagourait','daira_id' => '478'],
          ['nom' => 'Bou Haroun','daira_id' => '478'],
          ['nom' => 'Khemisti','daira_id' => '478'],
          ['nom' => 'Cherchell','daira_id' => '479'],
          ['nom' => 'Sidi Ghiles','daira_id' => '479'],
          ['nom' => 'Hadjeret Ennous','daira_id' => '479'],
          ['nom' => 'Sidi Semiane','daira_id' => '479'],
          ['nom' => 'Damous','daira_id' => '480'],
          ['nom' => 'Larhat','daira_id' => '480'],
          ['nom' => 'Beni Milleuk','daira_id' => '480'],
          ['nom' => 'Fouka','daira_id' => '481'],
          ['nom' => 'Douaouda','daira_id' => '481'],
          ['nom' => 'Gouraya','daira_id' => '482'],
          ['nom' => 'Messelmoun','daira_id' => '482'],
          ['nom' => 'Aghbal','daira_id' => '482'],
          ['nom' => 'Hadjout','daira_id' => '483'],
          ['nom' => 'Merad','daira_id' => '483'],
          ['nom' => 'Koléa','daira_id' => '484'],
          ['nom' => 'Chaiba','daira_id' => '484'],
          ['nom' => 'Attatba','daira_id' => '484'],
          ['nom' => 'Sidi Amar','daira_id' => '485'],
          ['nom' => 'Nador','daira_id' => '485'],
          ['nom' => 'Menaceur','daira_id' => '485'],
          ['nom' => 'Tipaza','daira_id' => '486'],
          ['nom' => 'Mila','daira_id' => '487'],
          ['nom' => 'Sidi Khelifa','daira_id' => '487'],
          ['nom' => 'Aïn Tine','daira_id' => '487'],
          ['nom' => 'Chelghoum Laid','daira_id' => '488'],
          ['nom' => 'Aïn Mellouk','daira_id' => '488'],
          ['nom' => 'Oued Athmania','daira_id' => '488'],
          ['nom' => 'Ferdjioua','daira_id' => '489'],
          ['nom' => 'Yahia Beni Guecha','daira_id' => '489'],
          ['nom' => 'Grarem Gouga','daira_id' => '490'],
          ['nom' => 'Hamala','daira_id' => '490'],
          ['nom' => 'Oued Endja','daira_id' => '491'],
          ['nom' => 'Zeghaia','daira_id' => '491'],
          ['nom' => 'Ahmed Rachedi','daira_id' => '491'],
          ['nom' => 'Rouached','daira_id' => '492'],
          ['nom' => 'Tiberguent','daira_id' => '492'],
          ['nom' => 'Terrai Bainen','daira_id' => '493'],
          ['nom' => 'Amira Arrès','daira_id' => '493'],
          ['nom' => 'Tessala Lemtaï','daira_id' => '493'],
          ['nom' => 'Tassadane Haddada','daira_id' => '494'],
          ['nom' => 'Minar Zarza','daira_id' => '494'],
          ['nom' => 'Aïn Beida Harriche','daira_id' => '495'],
          ['nom' => 'Elayadi Barbes','daira_id' => '495'],
          ['nom' => 'Sidi Merouane','daira_id' => '496'],
          ['nom' => 'Chigara','daira_id' => '496'],
          ['nom' => 'Teleghma','daira_id' => '497'],
          ['nom' => 'Oued Seguen','daira_id' => '497'],
          ['nom' => 'El Mechira','daira_id' => '497'],
          ['nom' => 'Bouhatem','daira_id' => '498'],
          ['nom' => 'Derrahi Bousselah','daira_id' => '498'],
          ['nom' => 'Tadjenanet','daira_id' => '499'],
          ['nom' => 'Benyahia Abderrahmane','daira_id' => '499'],
          ['nom' => 'Ouled Khalouf','daira_id' => '499'],
          ['nom' => 'Aïn Defla','daira_id' => '500'],
          ['nom' => 'Aïn Lechiekh','daira_id' => '501'],
          ['nom' => 'Aïn Soltane','daira_id' => '501'],
          ['nom' => 'Oued Djemaa','daira_id' => '501'],
          ['nom' => 'Bathia','daira_id' => '502'],
          ['nom' => 'El Hassania','daira_id' => '502'],
          ['nom' => 'Belaas','daira_id' => '502'],
          ['nom' => 'Bordj Emir Khaled','daira_id' => '503'],
          ['nom' => 'Bir Ould Khelifa','daira_id' => '503'],
          ['nom' => 'Tarik Ibn Ziad','daira_id' => '503'],
          ['nom' => 'Boumedfaa','daira_id' => '504'],
          ['nom' => 'Hoceinia','daira_id' => '504'],
          ['nom' => 'Djelida','daira_id' => '505'],
          ['nom' => 'Bourached','daira_id' => '505'],
          ['nom' => 'Djemaa Ouled Cheikh','daira_id' => '505'],
          ['nom' => 'Djendel','daira_id' => '506'],
          ['nom' => 'Birbouche','daira_id' => '506'],
          ['nom' => 'Oued Chorfa','daira_id' => '506'],
          ['nom' => 'El Abadia','daira_id' => '507'],
          ['nom' => 'Aïn Bouyahia','daira_id' => '507'],
          ['nom' => 'Tacheta Zougagha','daira_id' => '507'],
          ['nom' => 'El Amra','daira_id' => '508'],
          ['nom' => 'Arib','daira_id' => '508'],
          ['nom' => 'Mekhatria','daira_id' => '508'],
          ['nom' => 'El Attaf','daira_id' => '509'],
          ['nom' => 'Tiberkanine','daira_id' => '509'],
          ['nom' => 'Hammam Righa','daira_id' => '510'],
          ['nom' => 'Aïn Benian','daira_id' => '510'],
          ['nom' => 'Aïn Torki','daira_id' => '510'],
          ['nom' => 'Khemis Miliana','daira_id' => '511'],
          ['nom' => 'Sidi Lakhdar','daira_id' => '511'],
          ['nom' => 'Miliana','daira_id' => '512'],
          ['nom' => 'Ben Allal','daira_id' => '512'],
          ['nom' => 'El Maine','daira_id' => '513'],
          ['nom' => 'Rouina','daira_id' => '513'],
          ['nom' => 'Zeddine','daira_id' => '513'],
          ['nom' => 'Naâma','daira_id' => '514'],
          ['nom' => 'Ain Sefra','daira_id' => '515'],
          ['nom' => 'Tiout','daira_id' => '515'],
          ['nom' => 'Assela','daira_id' => '516'],
          ['nom' => 'Makman Ben Amer','daira_id' => '517'],
          ['nom' => 'Kasdir','daira_id' => '517'],
          ['nom' => 'Méchria','daira_id' => '518'],
          ['nom' => 'Aïn Ben Khelil','daira_id' => '518'],
          ['nom' => 'El Biod','daira_id' => '518'],
          ['nom' => 'Moghrar','daira_id' => '519'],
          ['nom' => 'Djeniene Bourezg','daira_id' => '519'],
          ['nom' => 'Sfissifa','daira_id' => '520'],
          ['nom' => 'Aïn El Arbaa','daira_id' => '521'],
          ['nom' => 'Tamzoura','daira_id' => '521'],
          ['nom' => 'Sidi Boumedienne','daira_id' => '521'],
          ['nom' => 'Oued Sebbah','daira_id' => '521'],
          ['nom' => 'Aïn Kihal','daira_id' => '522'],
          ['nom' => 'Aghlal','daira_id' => '522'],
          ['nom' => 'Aïn Tolba','daira_id' => '522'],
          ['nom' => 'Aoubellil','daira_id' => '522'],
          ['nom' => 'Aïn Témouchent','daira_id' => '523'],
          ['nom' => 'Sidi Ben Adda','daira_id' => '523'],
          ['nom' => 'Beni Saf','daira_id' => '524'],
          ['nom' => 'Sidi Safi','daira_id' => '524'],
          ['nom' => 'El Emir Abdelkader','daira_id' => '524'],
          ['nom' => 'El Amria','daira_id' => '525'],
          ['nom' => 'Bouzedjar','daira_id' => '525'],
          ['nom' => 'Ouled Boudjemaa','daira_id' => '525'],
          ['nom' => 'M\'Said','daira_id' => '525'],
          ['nom' => 'Hassi El Ghella','daira_id' => '525'],
          ['nom' => 'El Malah','daira_id' => '526'],
          ['nom' => 'Terga','daira_id' => '526'],
          ['nom' => 'Chaabat El Leham','daira_id' => '526'],
          ['nom' => 'Ouled Kihal','daira_id' => '526'],
          ['nom' => 'Hammam Bou Hadjar','daira_id' => '527'],
          ['nom' => 'Oued Berkeche','daira_id' => '527'],
          ['nom' => 'Chentouf','daira_id' => '527'],
          ['nom' => 'Hassasna','daira_id' => '527'],
          ['nom' => 'Oulhaça El Gheraba','daira_id' => '528'],
          ['nom' => 'Sidi Ouriache','daira_id' => '528'],
          ['nom' => 'Ghardaïa','daira_id' => '529'],
          ['nom' => 'El Menia','daira_id' => '530'],
          ['nom' => 'Hassi Gara','daira_id' => '530'],
          ['nom' => 'Metlili','daira_id' => '531'],
          ['nom' => 'Sebseb','daira_id' => '531'],
          ['nom' => 'Berriane','daira_id' => '532'],
          ['nom' => 'Dhayet Bendhahoua','daira_id' => '533'],
          ['nom' => 'Mansoura','daira_id' => '534'],
          ['nom' => 'Hassi Fehal','daira_id' => '534'],
          ['nom' => 'Zelfana','daira_id' => '535'],
          ['nom' => 'El Guerrara','daira_id' => '536'],
          ['nom' => 'Bounoura','daira_id' => '537'],
          ['nom' => 'El Atteuf','daira_id' => '537'],
          ['nom' => 'Aïn Tarek','daira_id' => '538'],
          ['nom' => 'Had Echkalla','daira_id' => '538'],
          ['nom' => 'Ammi Moussa','daira_id' => '540'],
          ['nom' => 'El Hassi','daira_id' => '540'],
          ['nom' => 'El Ouldja','daira_id' => '540'],
          ['nom' => 'Ouled Aiche','daira_id' => '540'],
          ['nom' => 'Djidioua','daira_id' => '541'],
          ['nom' => 'Hamri','daira_id' => '541'],
          ['nom' => 'Ouled Sidi Mihoub','daira_id' => '541'],
          ['nom' => 'El Hamadna','daira_id' => '542'],
          ['nom' => 'Oued El Djemaa','daira_id' => '542'],
          ['nom' => 'El Matmar','daira_id' => '543'],
          ['nom' => 'Belassel Bouzegza','daira_id' => '543'],
          ['nom' => 'Sidi Khettab','daira_id' => '543'],
          ['nom' => 'Sidi M\'Hamed Benaouda','daira_id' => '543'],
          ['nom' => 'Mazouna','daira_id' => '544'],
          ['nom' => 'El Guettar','daira_id' => '544'],
          ['nom' => 'Mendes','daira_id' => '545'],
          ['nom' => 'Oued Essalem','daira_id' => '545'],
          ['nom' => 'Sidi Lazreg','daira_id' => '545'],
          ['nom' => 'Oued Rhiou','daira_id' => '546'],
          ['nom' => 'Merdja Sidi Abed','daira_id' => '546'],
          ['nom' => 'Ouarizane','daira_id' => '546'],
          ['nom' => 'Lahlef','daira_id' => '546'],
          ['nom' => 'Ramka','daira_id' => '547'],
          ['nom' => 'Souk El Had','daira_id' => '547'],
          ['nom' => 'Relizane','daira_id' => '548'],
          ['nom' => 'Bendaoud','daira_id' => '548'],
          ['nom' => 'Sidi M\'Hamed Ben Ali','daira_id' => '549'],
          ['nom' => 'Beni Zentis','daira_id' => '549'],
          ['nom' => 'Mediouna','daira_id' => '549'],
          ['nom' => 'Yellel','daira_id' => '550'],
          ['nom' => 'Aïn Rahma','daira_id' => '550'],
          ['nom' => 'Kalaa','daira_id' => '550'],
          ['nom' => 'Sidi Saada','daira_id' => '550'],
          ['nom' => 'Zemmora','daira_id' => '551'],
          ['nom' => 'Beni Dergoun','daira_id' => '551'],
          ['nom' => 'Dar Ben Abdellah','daira_id' => '551']
        ];

      DB::table('communes')->insert($data);
    }
}
