<?php

use Illuminate\Database\Seeder;

class dairas extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dairas = [
        	['id' => '1','nom' => 'Adrar','wilaya_id' => '1'],
        	['id' => '2','nom' => 'Aoulef','wilaya_id' => '1'],
        	['id' => '3','nom' => 'Aougrout','wilaya_id' => '1'],
        	['id' => '4','nom' => 'Bordj Badji Mokhtar','wilaya_id' => '1'],
        	['id' => '5','nom' => 'Charouine','wilaya_id' => '1'],
        	['id' => '6','nom' => 'Fenoughil','wilaya_id' => '1'],
        	['id' => '7','nom' => 'Reggane','wilaya_id' => '1'],
        	['id' => '8','nom' => 'Timimoun','wilaya_id' => '1'],
        	['id' => '9','nom' => 'Tinerkouk','wilaya_id' => '1'],
        	['id' => '10','nom' => 'Tsabit','wilaya_id' => '1'],
        	['id' => '11','nom' => 'Zaouiet Kounta','wilaya_id' => '1'],
        	['id' => '12','nom' => 'Chlef','wilaya_id' => '2'],
        	['id' => '13','nom' => 'Abou El Hassan','wilaya_id' => '2'],
        	['id' => '14','nom' => 'El Karimia','wilaya_id' => '2'],
        	['id' => '15','nom' => 'Beni Haoua','wilaya_id' => '2'],
        	['id' => '16','nom' => 'Ouled Fares','wilaya_id' => '2'],
        	['id' => '17','nom' => 'El Marsa','wilaya_id' => '2'],
        	['id' => '18','nom' => 'Taougrite','wilaya_id' => '2'],
        	['id' => '19','nom' => 'Oued Fodda','wilaya_id' => '2'],
        	['id' => '20','nom' => 'Ténès','wilaya_id' => '2'],
        	['id' => '21','nom' => 'Ouled Ben Abdelkader','wilaya_id' => '2'],
        	['id' => '22','nom' => 'Aïn Merane','wilaya_id' => '2'],
        	['id' => '23','nom' => 'Boukadir','wilaya_id' => '2'],
        	['id' => '24','nom' => 'Zeboudja','wilaya_id' => '2'],
        	['id' => '25','nom' => 'Aflou','wilaya_id' => '3'],
        	['id' => '26','nom' => 'Aïn Mahdi','wilaya_id' => '3'],
        	['id' => '27','nom' => 'Brida','wilaya_id' => '3'],
        	['id' => '28','nom' => 'El Ghicha','wilaya_id' => '3'],
        	['id' => '29','nom' => 'Gueltet Sidi Saâd','wilaya_id' => '3'],
        	['id' => '30','nom' => 'Hassi R\'Mel','wilaya_id' => '3'],
        	['id' => '31','nom' => 'Ksar El Hirane','wilaya_id' => '3'],
        	['id' => '32','nom' => 'Laghouat','wilaya_id' => '3'],
        	['id' => '33','nom' => 'Oued Morra','wilaya_id' => '3'],
        	['id' => '34','nom' => 'Sidi Makhlouf','wilaya_id' => '3'],
        	['id' => '35','nom' => 'Aïn Babouche','wilaya_id' => '4'],
        	['id' => '36','nom' => 'Aïn Beïda','wilaya_id' => '4'],
        	['id' => '37','nom' => 'Aïn Fakroun','wilaya_id' => '4'],
        	['id' => '38','nom' => 'Aïn Kercha','wilaya_id' => '4'],
        	['id' => '39','nom' => 'Aïn M’lila','wilaya_id' => '4'],
        	['id' => '40','nom' => 'Dhalaa','wilaya_id' => '4'],
        	['id' => '41','nom' => 'Fkirina','wilaya_id' => '4'],
        	['id' => '42','nom' => 'Ksar Sbahi','wilaya_id' => '4'],
        	['id' => '43','nom' => 'Meskiana','wilaya_id' => '4'],
	        ['id' => '44','nom' => 'Oum El Bouaghi','wilaya_id' => '4'],
	        ['id' => '45','nom' => 'Sigus','wilaya_id' => '4'],
	        ['id' => '46','nom' => 'Souk Naamane','wilaya_id' => '4'],
	        ['id' => '47','nom' => 'Aïn Djasser','wilaya_id' => '5'],
	        ['id' => '48','nom' => 'Aïn Touta','wilaya_id' => '5'],
	        ['id' => '49','nom' => 'Arris','wilaya_id' => '5'],
	        ['id' => '50','nom' => 'Barika','wilaya_id' => '5'],
	        ['id' => '51','nom' => 'Batna','wilaya_id' => '5'],
	        ['id' => '52','nom' => 'Bouzina','wilaya_id' => '5'],
	        ['id' => '53','nom' => 'Chemora','wilaya_id' => '5'],
	        ['id' => '54','nom' => 'Djezzar','wilaya_id' => '5'],
	        ['id' => '55','nom' => 'El Madher','wilaya_id' => '5'],
	        ['id' => '56','nom' => 'Ichmoul','wilaya_id' => '5'],
	        ['id' => '57','nom' => 'Menaa','wilaya_id' => '5'],
	        ['id' => '58','nom' => 'Merouana','wilaya_id' => '5'],
	        ['id' => '59','nom' => 'N\'Gaous','wilaya_id' => '5'],
	        ['id' => '60','nom' => 'Ouled Si Slimane','wilaya_id' => '5'],
	        ['id' => '61','nom' => 'Ras El Aioun','wilaya_id' => '5'],
	        ['id' => '62','nom' => 'Seggana','wilaya_id' => '5'],
	        ['id' => '63','nom' => 'Seriana','wilaya_id' => '5'],
	        ['id' => '64','nom' => 'Tazoult','wilaya_id' => '5'],
	        ['id' => '65','nom' => 'Teniet El Abed','wilaya_id' => '5'],
	        ['id' => '66','nom' => 'Timgad','wilaya_id' => '5'],
	        ['id' => '67','nom' => 'T\'kout','wilaya_id' => '5'],
	        ['id' => '68','nom' => 'Adekar','wilaya_id' => '6'],
	        ['id' => '69','nom' => 'Akbou','wilaya_id' => '6'],
	        ['id' => '70','nom' => 'Amizour','wilaya_id' => '6'],
	        ['id' => '71','nom' => 'Aokas','wilaya_id' => '6'],
	        ['id' => '72','nom' => 'Barbacha','wilaya_id' => '6'],
	        ['id' => '73','nom' => 'Béjaïa','wilaya_id' => '6'],
	        ['id' => '74','nom' => 'Beni Maouche','wilaya_id' => '6'],
	        ['id' => '75','nom' => 'Chemini','wilaya_id' => '6'],
	        ['id' => '76','nom' => 'Darguina','wilaya_id' => '6'],
	        ['id' => '77','nom' => 'El Kseur','wilaya_id' => '6'],
	        ['id' => '78','nom' => 'Ighil Ali','wilaya_id' => '6'],
	        ['id' => '79','nom' => 'Kherrata','wilaya_id' => '6'],
	        ['id' => '80','nom' => 'Ouzellaguen','wilaya_id' => '6'],
	        ['id' => '81','nom' => 'Seddouk','wilaya_id' => '6'],
	        ['id' => '82','nom' => 'Sidi-Aïch','wilaya_id' => '6'],
	        ['id' => '83','nom' => 'Souk El-Ténine','wilaya_id' => '6'],
	        ['id' => '84','nom' => 'Tazmalt','wilaya_id' => '6'],
	        ['id' => '85','nom' => 'Tichy','wilaya_id' => '6'],
	        ['id' => '86','nom' => 'Timezrit','wilaya_id' => '6'],
	        ['id' => '87','nom' => 'Biskra','wilaya_id' => '7'],
	        ['id' => '88','nom' => 'Djemoura','wilaya_id' => '7'],
	        ['id' => '89','nom' => 'El Kantara','wilaya_id' => '7'],
	        ['id' => '90','nom' => 'M’Chouneche','wilaya_id' => '7'],
	        ['id' => '91','nom' => 'Sidi Okba','wilaya_id' => '7'],
	        ['id' => '92','nom' => 'Zeribet El Oued ','wilaya_id' => '7'],
	        ['id' => '93','nom' => 'Ourlal','wilaya_id' => '7'],
	        ['id' => '94','nom' => 'Tolga ','wilaya_id' => '7'],
	        ['id' => '95','nom' => 'Ouled Djellal','wilaya_id' => '7'],
	        ['id' => '96','nom' => 'Sidi Khaled','wilaya_id' => '7'],
	        ['id' => '97','nom' => 'Foughala','wilaya_id' => '7'],
	        ['id' => '98','nom' => 'El Outaya','wilaya_id' => '7'],
	        ['id' => '99','nom' => 'Béchar','wilaya_id' => '8'],
	        ['id' => '100','nom' => 'Beni Ounif','wilaya_id' => '8'],
	        ['id' => '101','nom' => 'Lahmar','wilaya_id' => '8'],
	        ['id' => '102','nom' => 'Kenadsa','wilaya_id' => '8'],
	        ['id' => '103','nom' => 'Taghit','wilaya_id' => '8'],
	        ['id' => '104','nom' => 'Abadla','wilaya_id' => '8'],
	        ['id' => '105','nom' => 'Tabelbala','wilaya_id' => '8'],
	        ['id' => '106','nom' => 'Igli','wilaya_id' => '8'],
	        ['id' => '107','nom' => 'Beni Abbes','wilaya_id' => '8'],
	        ['id' => '108','nom' => 'El Ouata','wilaya_id' => '8'],
	        ['id' => '109','nom' => 'Kerzaz','wilaya_id' => '8'],
	        ['id' => '110','nom' => 'Ouled Khoudir','wilaya_id' => '8'],
	        ['id' => '111','nom' => 'Blida','wilaya_id' => '9'],
	        ['id' => '112','nom' => 'Boufarik','wilaya_id' => '9'],
	        ['id' => '113','nom' => 'Bougara','wilaya_id' => '9'],
	        ['id' => '114','nom' => 'Bouinan','wilaya_id' => '9'],
	        ['id' => '115','nom' => 'El Affroun','wilaya_id' => '9'],
	        ['id' => '116','nom' => 'Larbaa','wilaya_id' => '9'],
	        ['id' => '117','nom' => 'Meftah','wilaya_id' => '9'],
	        ['id' => '118','nom' => 'Mouzaïa','wilaya_id' => '9'],
	        ['id' => '119','nom' => 'Oued Alleug','wilaya_id' => '9'],
	        ['id' => '120','nom' => 'Ouled Yaich','wilaya_id' => '9'],
	        ['id' => '121','nom' => 'Bouira','wilaya_id' => '10'],
	        ['id' => '122','nom' => 'Haizer','wilaya_id' => '10'],
	        ['id' => '123','nom' => 'Bechloul','wilaya_id' => '10'],
	        ['id' => '124','nom' => 'M\'Chedallah','wilaya_id' => '10'],
	        ['id' => '125','nom' => 'Kadiria','wilaya_id' => '10'],
	        ['id' => '126','nom' => 'Lakhdaria','wilaya_id' => '10'],
	        ['id' => '127','nom' => 'Bir Ghbalou','wilaya_id' => '10'],
	        ['id' => '128','nom' => 'Aïn Bessem','wilaya_id' => '10'],
	        ['id' => '129','nom' => 'Souk El Khemis','wilaya_id' => '10'],
	        ['id' => '130','nom' => 'El Hachimia','wilaya_id' => '10'],
	        ['id' => '131','nom' => 'Sour El-Ghozlane','wilaya_id' => '10'],
	        ['id' => '132','nom' => 'Bordj Okhriss','wilaya_id' => '10'],
	        ['id' => '133','nom' => 'Silet','wilaya_id' => '11'],
	        ['id' => '134','nom' => 'In Ghar','wilaya_id' => '11'],
	        ['id' => '135','nom' => 'In Guezzam','wilaya_id' => '11'],
	        ['id' => '136','nom' => 'In Salah','wilaya_id' => '11'],
	        ['id' => '137','nom' => 'Tazrouk','wilaya_id' => '11'],
	        ['id' => '138','nom' => 'Tamanrasset','wilaya_id' => '11'],
	        ['id' => '139','nom' => 'Tinzaouten','wilaya_id' => '11'],
	        ['id' => '141','nom' => 'Tébessa','wilaya_id' => '12'],
	        ['id' => '142','nom' => 'El Kouif','wilaya_id' => '12'],
	        ['id' => '143','nom' => 'Morsott','wilaya_id' => '12'],
	        ['id' => '144','nom' => 'El Ma Labiodh','wilaya_id' => '12'],
	        ['id' => '145','nom' => 'El Aouinet','wilaya_id' => '12'],
	        ['id' => '146','nom' => 'Ouenza','wilaya_id' => '12'],
	        ['id' => '147','nom' => 'Bir Mokkadem','wilaya_id' => '12'],
	        ['id' => '148','nom' => 'Bir el-Ater','wilaya_id' => '12'],
	        ['id' => '149','nom' => 'El Ogla','wilaya_id' => '12'],
	        ['id' => '150','nom' => 'Oum Ali','wilaya_id' => '12'],
	        ['id' => '151','nom' => 'Negrine','wilaya_id' => '12'],
	        ['id' => '152','nom' => 'Cheria','wilaya_id' => '12'],
	        ['id' => '153','nom' => 'Aïn Tallout','wilaya_id' => '13'],
	        ['id' => '154','nom' => 'Bab El Assa','wilaya_id' => '13'],
	        ['id' => '155','nom' => 'Hennaya','wilaya_id' => '13'],
	        ['id' => '156','nom' => 'Beni Boussaid','wilaya_id' => '13'],
	        ['id' => '157','nom' => 'Honaïne','wilaya_id' => '13'],
	        ['id' => '158','nom' => 'Beni Snous','wilaya_id' => '13'],
	        ['id' => '159','nom' => 'Bensekrane','wilaya_id' => '13'],
	        ['id' => '160','nom' => 'Chetouane','wilaya_id' => '13'],
	        ['id' => '161','nom' => 'Fellaoucene','wilaya_id' => '13'],
	        ['id' => '162','nom' => 'Ghazaouet ','wilaya_id' => '13'],
	        ['id' => '163','nom' => 'Maghnia','wilaya_id' => '13'],
	        ['id' => '164','nom' => 'Mansourah','wilaya_id' => '13'],
	        ['id' => '165','nom' => 'Marsa Ben M\'Hidi','wilaya_id' => '13'],
	        ['id' => '166','nom' => 'Nedroma','wilaya_id' => '13'],
	        ['id' => '167','nom' => 'Ouled Mimoun','wilaya_id' => '13'],
	        ['id' => '168','nom' => 'Remchi','wilaya_id' => '13'],
	        ['id' => '169','nom' => 'Sabra','wilaya_id' => '13'],
	        ['id' => '170','nom' => 'Sebdou','wilaya_id' => '13'],
	        ['id' => '171','nom' => 'Sidi Djillali','wilaya_id' => '13'],
	        ['id' => '172','nom' => 'Tlemcen','wilaya_id' => '13'],
	        ['id' => '173','nom' => 'Aïn Deheb','wilaya_id' => '14'],
	        ['id' => '174','nom' => 'Aïn Kermes','wilaya_id' => '14'],
	        ['id' => '175','nom' => 'Dahmouni','wilaya_id' => '14'],
	        ['id' => '176','nom' => 'Frenda','wilaya_id' => '14'],
	        ['id' => '177','nom' => 'Hamadia','wilaya_id' => '14'],
	        ['id' => '178','nom' => 'Ksar Chellala','wilaya_id' => '14'],
	        ['id' => '179','nom' => 'Mahdia','wilaya_id' => '14'],
	        ['id' => '180','nom' => 'Mechraa Safa','wilaya_id' => '14'],
	        ['id' => '181','nom' => 'Medroussa','wilaya_id' => '14'],
	        ['id' => '182','nom' => 'Meghila','wilaya_id' => '14'],
	        ['id' => '183','nom' => 'Oued Lilli','wilaya_id' => '14'],
	        ['id' => '184','nom' => 'Rahouia','wilaya_id' => '14'],
	        ['id' => '185','nom' => 'Sougueur','wilaya_id' => '14'],
	        ['id' => '186','nom' => 'Tiaret','wilaya_id' => '14'],
	        ['id' => '187','nom' => 'Ain El Hammam','wilaya_id' => '15'],
	        ['id' => '188','nom' => 'Azazga','wilaya_id' => '15'],
	        ['id' => '189','nom' => 'Azeffoun','wilaya_id' => '15'],
	        ['id' => '190','nom' => 'Aït Douala','wilaya_id' => '15'],
	        ['id' => '191','nom' => 'Aït Yenni','wilaya_id' => '15'],
	        ['id' => '192','nom' => 'Boghni','wilaya_id' => '15'],
	        ['id' => '193','nom' => 'Bouzeguène','wilaya_id' => '15'],
	        ['id' => '194','nom' => 'Draâ Ben Khedda','wilaya_id' => '15'],
	        ['id' => '195','nom' => 'Draâ El Mizan','wilaya_id' => '15'],
	        ['id' => '196','nom' => 'Iferhounène','wilaya_id' => '15'],
	        ['id' => '197','nom' => 'Larbaâ Nath Irathen','wilaya_id' => '15'],
	        ['id' => '198','nom' => 'Mâatkas','wilaya_id' => '15'],
	        ['id' => '199','nom' => 'Makouda','wilaya_id' => '15'],
	        ['id' => '200','nom' => 'Mekla','wilaya_id' => '15'],
	        ['id' => '201','nom' => 'Ouacif','wilaya_id' => '15'],
	        ['id' => '202','nom' => 'Ouadhia','wilaya_id' => '15'],
	        ['id' => '203','nom' => 'Ouaguenoun','wilaya_id' => '15'],
	        ['id' => '204','nom' => 'Tigzirt','wilaya_id' => '15'],
	        ['id' => '205','nom' => 'Tizi Gheniff','wilaya_id' => '15'],
	        ['id' => '206','nom' => 'Tizi Ouzou','wilaya_id' => '15'],
	        ['id' => '207','nom' => 'Tizi Rached','wilaya_id' => '15'],
	        ['id' => '208','nom' => 'Bab El Oued','wilaya_id' => '16'],
	        ['id' => '209','nom' => 'Baraki','wilaya_id' => '16'],
	        ['id' => '210','nom' => 'Bir Mourad Raïs','wilaya_id' => '16'],
	        ['id' => '211','nom' => 'Birtouta','wilaya_id' => '16'],
	        ['id' => '212','nom' => 'Bouzareah','wilaya_id' => '16'],
	        ['id' => '213','nom' => 'Chéraga','wilaya_id' => '16'],
	        ['id' => '214','nom' => 'Dar El Beïda','wilaya_id' => '16'],
	        ['id' => '215','nom' => 'Draria','wilaya_id' => '16'],
	        ['id' => '216','nom' => 'El Harrach','wilaya_id' => '16'],
	        ['id' => '217','nom' => 'Hussein Dey','wilaya_id' => '16'],
	        ['id' => '218','nom' => 'Rouïba','wilaya_id' => '16'],
	        ['id' => '219','nom' => 'Sidi M\'Hamed','wilaya_id' => '16'],
	        ['id' => '220','nom' => 'Zéralda','wilaya_id' => '16'],
	        ['id' => '221','nom' => 'Djelfa','wilaya_id' => '17'],
	        ['id' => '222','nom' => 'Aïn El Ibel','wilaya_id' => '17'],
	        ['id' => '223','nom' => 'Aïn Oussara','wilaya_id' => '17'],
	        ['id' => '224','nom' => 'Birine','wilaya_id' => '17'],
	        ['id' => '225','nom' => 'Hassi Bahbah','wilaya_id' => '17'],
	        ['id' => '226','nom' => 'Charef','wilaya_id' => '17'],
	        ['id' => '227','nom' => 'Dar Chioukh','wilaya_id' => '17'],
	        ['id' => '228','nom' => 'El Idrissia','wilaya_id' => '17'],
	        ['id' => '229','nom' => 'Faidh El Botma','wilaya_id' => '17'],
	        ['id' => '230','nom' => 'Had-Sahary','wilaya_id' => '17'],
	        ['id' => '231','nom' => 'Messaad','wilaya_id' => '17'],
	        ['id' => '232','nom' => 'Sidi Ladjel','wilaya_id' => '17'],
	        ['id' => '233','nom' => 'Chekfa','wilaya_id' => '18'],
	        ['id' => '234','nom' => 'Djimla','wilaya_id' => '18'],
	        ['id' => '235','nom' => 'El Ancer','wilaya_id' => '18'],
	        ['id' => '236','nom' => 'El Aouana','wilaya_id' => '18'],
	        ['id' => '237','nom' => 'El Milia','wilaya_id' => '18'],
	        ['id' => '238','nom' => 'Jijel','wilaya_id' => '18'],
	        ['id' => '239','nom' => 'Settara','wilaya_id' => '18'],
	        ['id' => '240','nom' => 'Sidi Maarouf','wilaya_id' => '18'],
	        ['id' => '241','nom' => 'Taher','wilaya_id' => '18'],
	        ['id' => '242','nom' => 'Texenna','wilaya_id' => '18'],
	        ['id' => '243','nom' => 'Ziama Mansouriah','wilaya_id' => '18'],
	        ['id' => '244','nom' => 'Aïn Arnat','wilaya_id' => '19'],
	        ['id' => '245','nom' => 'Aïn Azel','wilaya_id' => '19'],
	        ['id' => '246','nom' => 'Aïn El Kebira','wilaya_id' => '19'],
	        ['id' => '247','nom' => 'Aïn Oulmene','wilaya_id' => '19'],
	        ['id' => '248','nom' => 'Amoucha','wilaya_id' => '19'],
	        ['id' => '249','nom' => 'Babor','wilaya_id' => '19'],
	        ['id' => '250','nom' => 'Beni Aziz','wilaya_id' => '19'],
	        ['id' => '251','nom' => 'Beni Ourtilane','wilaya_id' => '19'],
	        ['id' => '252','nom' => 'Bir El Arch','wilaya_id' => '19'],
	        ['id' => '253','nom' => 'Bouandas','wilaya_id' => '19'],
	        ['id' => '254','nom' => 'Bougaa','wilaya_id' => '19'],
	        ['id' => '255','nom' => 'Djemila','wilaya_id' => '19'],
	        ['id' => '256','nom' => 'El Eulma','wilaya_id' => '19'],
	        ['id' => '257','nom' => 'Guidjel','wilaya_id' => '19'],
	        ['id' => '258','nom' => 'Guenzet','wilaya_id' => '19'],
	        ['id' => '259','nom' => 'Hammam Guergour','wilaya_id' => '19'],
	        ['id' => '260','nom' => 'Hammam Soukhna','wilaya_id' => '19'],
	        ['id' => '261','nom' => 'Maoklane','wilaya_id' => '19'],
	        ['id' => '262','nom' => 'Salah Bey','wilaya_id' => '19'],
	        ['id' => '263','nom' => 'Sétif','wilaya_id' => '19'],
	        ['id' => '264','nom' => 'Saïda','wilaya_id' => '20'],
	        ['id' => '265','nom' => 'Aïn El Hadjar','wilaya_id' => '20'],
	        ['id' => '266','nom' => 'Sidi Boubekeur','wilaya_id' => '20'],
	        ['id' => '267','nom' => 'El Hassasna','wilaya_id' => '20'],
	        ['id' => '268','nom' => 'Ouled Brahim','wilaya_id' => '20'],
	        ['id' => '269','nom' => 'Youb','wilaya_id' => '20'],
	        ['id' => '270','nom' => 'Aïn Kechra','wilaya_id' => '21'],
	        ['id' => '271','nom' => 'Azzaba','wilaya_id' => '21'],
	        ['id' => '272','nom' => 'Ben Azzouz','wilaya_id' => '21'],
	        ['id' => '273','nom' => 'Collo','wilaya_id' => '21'],
	        ['id' => '274','nom' => 'El Hadaiek','wilaya_id' => '21'],
	        ['id' => '275','nom' => 'El Harrouch','wilaya_id' => '21'],
	        ['id' => '276','nom' => 'Ouled Attia','wilaya_id' => '21'],
	        ['id' => '277','nom' => 'Oum Toub','wilaya_id' => '21'],
	        ['id' => '278','nom' => 'Ramdane Djamel','wilaya_id' => '21'],
	        ['id' => '279','nom' => 'Sidi Mezghiche','wilaya_id' => '21'],
	        ['id' => '280','nom' => 'Skikda','wilaya_id' => '21'],
	        ['id' => '281','nom' => 'Tamalous','wilaya_id' => '21'],
	        ['id' => '282','nom' => 'Zitouna','wilaya_id' => '21'],
	        ['id' => '283','nom' => 'Sidi Bel Abbès','wilaya_id' => '22'],
	        ['id' => '284','nom' => 'Ain El Berd','wilaya_id' => '22'],
	        ['id' => '285','nom' => 'Ben Badis','wilaya_id' => '22'],
	        ['id' => '286','nom' => 'Marhoum','wilaya_id' => '22'],
	        ['id' => '287','nom' => 'Merine','wilaya_id' => '22'],
	        ['id' => '288','nom' => 'Mostefa Ben Brahim','wilaya_id' => '22'],
	        ['id' => '289','nom' => 'Moulay Slissen','wilaya_id' => '22'],
	        ['id' => '290','nom' => 'Ras El Ma','wilaya_id' => '22'],
	        ['id' => '291','nom' => 'Sfisef','wilaya_id' => '22'],
	        ['id' => '292','nom' => 'Sidi Ali Benyoub','wilaya_id' => '22'],
	        ['id' => '293','nom' => 'Sidi Ali Boussidi','wilaya_id' => '22'],
	        ['id' => '294','nom' => 'Sidi Lahcene','wilaya_id' => '22'],
	        ['id' => '295','nom' => 'Telagh','wilaya_id' => '22'],
	        ['id' => '296','nom' => 'Tenira','wilaya_id' => '22'],
	        ['id' => '297','nom' => 'Tessala','wilaya_id' => '22'],
	        ['id' => '298','nom' => 'Annaba','wilaya_id' => '23'],
	        ['id' => '299','nom' => 'Aïn Berda','wilaya_id' => '23'],
	        ['id' => '300','nom' => 'El Hadjar','wilaya_id' => '23'],
	        ['id' => '301','nom' => 'Berrahal','wilaya_id' => '23'],
	        ['id' => '302','nom' => 'Chetaïbi','wilaya_id' => '23'],
	        ['id' => '303','nom' => 'El Bouni','wilaya_id' => '23'],
	        ['id' => '304','nom' => 'Guelma','wilaya_id' => '24'],
	        ['id' => '305','nom' => 'Khezarra','wilaya_id' => '24'],
	        ['id' => '306','nom' => 'Guelaat BouSbâa','wilaya_id' => '24'],
	        ['id' => '307','nom' => 'Héliopolis','wilaya_id' => '24'],
	        ['id' => '308','nom' => 'Oued Zenati','wilaya_id' => '24'],
	        ['id' => '309','nom' => 'Ain Makhlouf','wilaya_id' => '24'],
	        ['id' => '310','nom' => 'Hammam Debagh','wilaya_id' => '24'],
	        ['id' => '311','nom' => 'Bouchegouf','wilaya_id' => '24'],
	        ['id' => '312','nom' => 'Hammam N’Bails','wilaya_id' => '24'],
	        ['id' => '313','nom' => 'Ain Hessaïnia','wilaya_id' => '24'],
	        ['id' => '315','nom' => 'Constantine','wilaya_id' => '25'],
	        ['id' => '316','nom' => 'El Khroub','wilaya_id' => '25'],
	        ['id' => '317','nom' => 'Aïn Abid','wilaya_id' => '25'],
	        ['id' => '318','nom' => 'Zighoud Youcef','wilaya_id' => '25'],
	        ['id' => '319','nom' => 'Hamma Bouziane','wilaya_id' => '25'],
	        ['id' => '320','nom' => 'Ibn Ziad','wilaya_id' => '25'],
	        ['id' => '321','nom' => 'Aïn Boucif','wilaya_id' => '26'],
	        ['id' => '322','nom' => 'Aziz','wilaya_id' => '26'],
	        ['id' => '323','nom' => 'Beni Slimane','wilaya_id' => '26'],
	        ['id' => '324','nom' => 'Berrouaghia','wilaya_id' => '26'],
	        ['id' => '325','nom' => 'Chahbounia','wilaya_id' => '26'],
	        ['id' => '326','nom' => 'Chellalet El Adhaoura','wilaya_id' => '26'],
	        ['id' => '327','nom' => 'El Azizia','wilaya_id' => '26'],
	        ['id' => '328','nom' => 'El Guelb El Kebir','wilaya_id' => '26'],
	        ['id' => '329','nom' => 'El Omaria','wilaya_id' => '26'],
	        ['id' => '330','nom' => 'Ksar Boukhari','wilaya_id' => '26'],
	        ['id' => '331','nom' => 'Médéa','wilaya_id' => '26'],
	        ['id' => '332','nom' => 'Ouamri','wilaya_id' => '26'],
	        ['id' => '333','nom' => 'Ouled Antar','wilaya_id' => '26'],
	        ['id' => '334','nom' => 'Ouzera','wilaya_id' => '26'],
	        ['id' => '335','nom' => 'Seghouane','wilaya_id' => '26'],
	        ['id' => '336','nom' => 'Sidi Naamane','wilaya_id' => '26'],
	        ['id' => '337','nom' => 'Si Mahdjoub','wilaya_id' => '26'],
	        ['id' => '338','nom' => 'Souagui','wilaya_id' => '26'],
	        ['id' => '339','nom' => 'Tablat','wilaya_id' => '26'],
	        ['id' => '340','nom' => 'Mostaganem','wilaya_id' => '27'],
	        ['id' => '341','nom' => 'Hassi Maameche','wilaya_id' => '27'],
	        ['id' => '342','nom' => 'Ain Tedles','wilaya_id' => '27'],
	        ['id' => '343','nom' => 'Bouguirat','wilaya_id' => '27'],
	        ['id' => '344','nom' => 'Sidi Ali','wilaya_id' => '27'],
	        ['id' => '345','nom' => 'Achaacha','wilaya_id' => '27'],
	        ['id' => '346','nom' => 'Ain Nouissi','wilaya_id' => '27'],
	        ['id' => '347','nom' => 'Mesra','wilaya_id' => '27'],
	        ['id' => '348','nom' => 'Sidi Lakhdar','wilaya_id' => '27'],
	        ['id' => '349','nom' => 'Kheireddine','wilaya_id' => '27'],
	        ['id' => '350','nom' => 'M\'Sila','wilaya_id' => '28'],
	        ['id' => '351','nom' => 'Hammam Dalaa','wilaya_id' => '28'],
	        ['id' => '352','nom' => 'Ouled Derradj','wilaya_id' => '28'],
	        ['id' => '353','nom' => 'Sidi Aissa','wilaya_id' => '28'],
	        ['id' => '354','nom' => 'Aïn El Melh','wilaya_id' => '28'],
	        ['id' => '355','nom' => 'Ben Srour','wilaya_id' => '28'],
	        ['id' => '356','nom' => 'Bou Saada','wilaya_id' => '28'],
	        ['id' => '357','nom' => 'Ouled sidi Brahim','wilaya_id' => '28'],
	        ['id' => '358','nom' => 'Sidi Ameur','wilaya_id' => '28'],
	        ['id' => '359','nom' => 'Magra','wilaya_id' => '28'],
	        ['id' => '360','nom' => 'Chellal','wilaya_id' => '28'],
	        ['id' => '361','nom' => 'Khoubana','wilaya_id' => '28'],
	        ['id' => '362','nom' => 'Medjedel','wilaya_id' => '28'],
	        ['id' => '363','nom' => 'Aïn El Hadjel','wilaya_id' => '28'],
	        ['id' => '364','nom' => 'Djebel Messaad','wilaya_id' => '28'],
	        ['id' => '365','nom' => 'Aïn Fares','wilaya_id' => '29'],
	        ['id' => '366','nom' => 'Aïn Fekan','wilaya_id' => '29'],
	        ['id' => '367','nom' => 'Aouf','wilaya_id' => '29'],
	        ['id' => '368','nom' => 'Bou Hanifia','wilaya_id' => '29'],
	        ['id' => '369','nom' => 'El Bordj','wilaya_id' => '29'],
	        ['id' => '370','nom' => 'Ghriss','wilaya_id' => '29'],
	        ['id' => '371','nom' => 'Hachem','wilaya_id' => '29'],
	        ['id' => '372','nom' => 'Mascara','wilaya_id' => '29'],
	        ['id' => '373','nom' => 'Mohammadia','wilaya_id' => '29'],
	        ['id' => '374','nom' => 'Oggaz','wilaya_id' => '29'],
	        ['id' => '375','nom' => 'Oued El Abtal','wilaya_id' => '29'],
	        ['id' => '376','nom' => 'Oued Taria','wilaya_id' => '29'],
	        ['id' => '377','nom' => 'Sig','wilaya_id' => '29'],
	        ['id' => '378','nom' => 'Tighennif','wilaya_id' => '29'],
	        ['id' => '379','nom' => 'Tizi','wilaya_id' => '29'],
	        ['id' => '380','nom' => 'Zahana','wilaya_id' => '29'],
	        ['id' => '381','nom' => 'El Borma','wilaya_id' => '30'],
	        ['id' => '382','nom' => 'El Hadjira','wilaya_id' => '30'],
	        ['id' => '383','nom' => 'Hassi Messaoud','wilaya_id' => '30'],
	        ['id' => '384','nom' => 'Megarine','wilaya_id' => '30'],
	        ['id' => '385','nom' => 'N\'Goussa','wilaya_id' => '30'],
	        ['id' => '386','nom' => 'Ouargla','wilaya_id' => '30'],
	        ['id' => '387','nom' => 'Sidi Khouiled','wilaya_id' => '30'],
	        ['id' => '388','nom' => 'Taibet','wilaya_id' => '30'],
	        ['id' => '389','nom' => 'Tamacine','wilaya_id' => '30'],
	        ['id' => '390','nom' => 'Touggourt','wilaya_id' => '30'],
	        ['id' => '392','nom' => 'Oran','wilaya_id' => '31'],
	        ['id' => '393','nom' => 'Aïn El Turk','wilaya_id' => '31'],
	        ['id' => '394','nom' => 'Arzew','wilaya_id' => '31'],
	        ['id' => '395','nom' => 'Bethioua','wilaya_id' => '31'],
	        ['id' => '396','nom' => 'Es Sénia','wilaya_id' => '31'],
	        ['id' => '397','nom' => 'Bir El Djir','wilaya_id' => '31'],
	        ['id' => '398','nom' => 'Boutlélis','wilaya_id' => '31'],
	        ['id' => '399','nom' => 'Oued Tlelat','wilaya_id' => '31'],
	        ['id' => '400','nom' => 'Gdyel','wilaya_id' => '31'],
	        ['id' => '401','nom' => 'El Bayadh','wilaya_id' => '32'],
	        ['id' => '402','nom' => 'Rogassa','wilaya_id' => '32'],
	        ['id' => '403','nom' => 'Brezina','wilaya_id' => '32'],
	        ['id' => '404','nom' => 'El Abiodh Sidi Cheikh','wilaya_id' => '32'],
	        ['id' => '405','nom' => 'Bougtoub','wilaya_id' => '32'],
	        ['id' => '406','nom' => 'Chellala','wilaya_id' => '32'],
	        ['id' => '407','nom' => 'Boussemghoun','wilaya_id' => '32'],
	        ['id' => '408','nom' => 'Boualem','wilaya_id' => '32'],
	        ['id' => '409','nom' => 'Illizi','wilaya_id' => '33'],
	        ['id' => '410','nom' => 'Djanet','wilaya_id' => '33'],
	        ['id' => '411','nom' => 'In Amenas','wilaya_id' => '33'],
	        ['id' => '412','nom' => 'Bordj Bou Arreridj','wilaya_id' => '34'],
	        ['id' => '413','nom' => 'Aïn Taghrout','wilaya_id' => '34'],
	        ['id' => '414','nom' => 'Ras El Oued','wilaya_id' => '34'],
	        ['id' => '415','nom' => 'Bordj Ghedir','wilaya_id' => '34'],
	        ['id' => '416','nom' => 'Bir Kasdali','wilaya_id' => '34'],
	        ['id' => '417','nom' => 'El Hamadia','wilaya_id' => '34'],
	        ['id' => '418','nom' => 'Mansoura','wilaya_id' => '34'],
	        ['id' => '419','nom' => 'Medjana','wilaya_id' => '34'],
	        ['id' => '420','nom' => 'Bordj Zemoura','wilaya_id' => '34'],
	        ['id' => '421','nom' => 'Djaafra','wilaya_id' => '34'],
	        ['id' => '422','nom' => 'Baghlia','wilaya_id' => '35'],
	        ['id' => '423','nom' => 'Bordj Ménaïel','wilaya_id' => '35'],
	        ['id' => '424','nom' => 'Boudouaou','wilaya_id' => '35'],
	        ['id' => '425','nom' => 'Boumerdès','wilaya_id' => '35'],
	        ['id' => '426','nom' => 'Dellys','wilaya_id' => '35'],
	        ['id' => '427','nom' => 'Isser','wilaya_id' => '35'],
	        ['id' => '428','nom' => 'Khemis El Khechna','wilaya_id' => '35'],
	        ['id' => '429','nom' => 'Naciria','wilaya_id' => '35'],
	        ['id' => '430','nom' => 'Thénia','wilaya_id' => '35'],
	        ['id' => '431','nom' => 'El Tarf','wilaya_id' => '36'],
	        ['id' => '432','nom' => 'El Kala','wilaya_id' => '36'],
	        ['id' => '433','nom' => 'Ben Mehidi','wilaya_id' => '36'],
	        ['id' => '434','nom' => 'Besbes','wilaya_id' => '36'],
	        ['id' => '435','nom' => 'Dréan','wilaya_id' => '36'],
	        ['id' => '436','nom' => 'Bouhadjar','wilaya_id' => '36'],
	        ['id' => '437','nom' => 'Bouteldja','wilaya_id' => '36'],
	        ['id' => '438','nom' => 'Tindouf','wilaya_id' => '37'],
	        ['id' => '439','nom' => 'Ammari','wilaya_id' => '38'],
	        ['id' => '440','nom' => 'Bordj Bou Naama','wilaya_id' => '38'],
	        ['id' => '441','nom' => 'Bordj El Emir Abdelkader','wilaya_id' => '38'],
	        ['id' => '442','nom' => 'Khemisti','wilaya_id' => '38'],
	        ['id' => '443','nom' => 'Lardjem','wilaya_id' => '38'],
	        ['id' => '444','nom' => 'Lazharia','wilaya_id' => '38'],
	        ['id' => '445','nom' => 'Theniet El Had','wilaya_id' => '38'],
	        ['id' => '446','nom' => 'Tissemsilt','wilaya_id' => '38'],
	        ['id' => '447','nom' => 'Bayadha','wilaya_id' => '39'],
	        ['id' => '448','nom' => 'Debila','wilaya_id' => '39'],
	        ['id' => '449','nom' => 'Djamaa','wilaya_id' => '39'],
	        ['id' => '450','nom' => 'El M\'Ghair','wilaya_id' => '39'],
	        ['id' => '451','nom' => 'El Oued','wilaya_id' => '39'],
	        ['id' => '452','nom' => 'Guemar','wilaya_id' => '39'],
	        ['id' => '453','nom' => 'Hassi Khalifa','wilaya_id' => '39'],
	        ['id' => '454','nom' => 'Magrane','wilaya_id' => '39'],
	        ['id' => '455','nom' => 'Mih Ouansa','wilaya_id' => '39'],
	        ['id' => '456','nom' => 'Reguiba','wilaya_id' => '39'],
	        ['id' => '457','nom' => 'Robbah','wilaya_id' => '39'],
	        ['id' => '458','nom' => 'Taleb Larbi','wilaya_id' => '39'],
	        ['id' => '459','nom' => 'Khenchela','wilaya_id' => '40'],
	        ['id' => '460','nom' => 'Babar','wilaya_id' => '40'],
	        ['id' => '461','nom' => 'Bouhmama','wilaya_id' => '40'],
	        ['id' => '462','nom' => 'Chechar','wilaya_id' => '40'],
	        ['id' => '463','nom' => 'El Hamma','wilaya_id' => '40'],
	        ['id' => '464','nom' => 'Kais','wilaya_id' => '40'],
	        ['id' => '465','nom' => 'Ouled Rechache','wilaya_id' => '40'],
	        ['id' => '466','nom' => 'Aïn Touila','wilaya_id' => '40'],
	        ['id' => '467','nom' => 'Bir Bou Haouch','wilaya_id' => '41'],
	        ['id' => '468','nom' => 'Heddada','wilaya_id' => '41'],
	        ['id' => '469','nom' => 'M\'daourouch','wilaya_id' => '41'],
	        ['id' => '470','nom' => 'Mechroha','wilaya_id' => '41'],
	        ['id' => '471','nom' => 'Merahna','wilaya_id' => '41'],
	        ['id' => '472','nom' => 'Ouled Driss','wilaya_id' => '41'],
	        ['id' => '473','nom' => 'Oum El Adhaim','wilaya_id' => '41'],
	        ['id' => '474','nom' => 'Sedrata','wilaya_id' => '41'],
	        ['id' => '475','nom' => 'Souk Ahras','wilaya_id' => '41'],
	        ['id' => '476','nom' => 'Taoura','wilaya_id' => '41'],
	        ['id' => '477','nom' => 'Ahmar El Ain','wilaya_id' => '42'],
	        ['id' => '478','nom' => 'Bou Ismail','wilaya_id' => '42'],
	        ['id' => '479','nom' => 'Cherchell','wilaya_id' => '42'],
	        ['id' => '480','nom' => 'Damous','wilaya_id' => '42'],
	        ['id' => '481','nom' => 'Fouka','wilaya_id' => '42'],
	        ['id' => '482','nom' => 'Gouraya','wilaya_id' => '42'],
	        ['id' => '483','nom' => 'Hadjout','wilaya_id' => '42'],
	        ['id' => '484','nom' => 'Koléa','wilaya_id' => '42'],
	        ['id' => '485','nom' => 'Sidi Amar','wilaya_id' => '42'],
	        ['id' => '486','nom' => 'Tipaza','wilaya_id' => '42'],
	        ['id' => '487','nom' => 'Mila','wilaya_id' => '43'],
	        ['id' => '488','nom' => 'Chelghoum Laïd','wilaya_id' => '43'],
	        ['id' => '489','nom' => 'Ferdjioua','wilaya_id' => '43'],
	        ['id' => '490','nom' => 'Grarem Gouga','wilaya_id' => '43'],
	        ['id' => '491','nom' => 'Oued Endja','wilaya_id' => '43'],
	        ['id' => '492','nom' => 'Rouached','wilaya_id' => '43'],
	        ['id' => '493','nom' => 'Terrai Bainen','wilaya_id' => '43'],
	        ['id' => '494','nom' => 'Tassadane Haddada','wilaya_id' => '43'],
	        ['id' => '495','nom' => 'Aïn Beida Harriche','wilaya_id' => '43'],
	        ['id' => '496','nom' => 'Sidi Merouane','wilaya_id' => '43'],
	        ['id' => '497','nom' => 'Teleghma','wilaya_id' => '43'],
	        ['id' => '498','nom' => 'Bouhatem','wilaya_id' => '43'],
	        ['id' => '499','nom' => 'Tadjenanet','wilaya_id' => '43'],
	        ['id' => '500','nom' => 'Aïn Defla','wilaya_id' => '44'],
	        ['id' => '501','nom' => 'Aïn Lechiekh','wilaya_id' => '44'],
	        ['id' => '502','nom' => 'Bathia','wilaya_id' => '44'],
	        ['id' => '503','nom' => 'Bordj Emir Khaled','wilaya_id' => '44'],
	        ['id' => '504','nom' => 'Boumedfaa','wilaya_id' => '44'],
	        ['id' => '505','nom' => 'Djelida','wilaya_id' => '44'],
	        ['id' => '506','nom' => 'Djendel','wilaya_id' => '44'],
	        ['id' => '507','nom' => 'El Abadia','wilaya_id' => '44'],
	        ['id' => '508','nom' => 'El Amra','wilaya_id' => '44'],
	        ['id' => '509','nom' => 'El Attaf','wilaya_id' => '44'],
	        ['id' => '510','nom' => 'Hammam Righa','wilaya_id' => '44'],
	        ['id' => '511','nom' => 'Khemis Miliana','wilaya_id' => '44'],
	        ['id' => '512','nom' => 'Miliana','wilaya_id' => '44'],
	        ['id' => '513','nom' => 'Rouina','wilaya_id' => '44'],
	        ['id' => '514','nom' => 'Naâma','wilaya_id' => '45'],
	        ['id' => '515','nom' => 'Ain Sefra','wilaya_id' => '45'],
	        ['id' => '516','nom' => 'Assela','wilaya_id' => '45'],
	        ['id' => '517','nom' => 'Makman Ben Amer','wilaya_id' => '45'],
	        ['id' => '518','nom' => 'Mecheria','wilaya_id' => '45'],
	        ['id' => '519','nom' => 'Moghrar','wilaya_id' => '45'],
	        ['id' => '520','nom' => 'Sfissifa','wilaya_id' => '45'],
	        ['id' => '521','nom' => 'Aïn El Arbaa','wilaya_id' => '46'],
	        ['id' => '522','nom' => 'Ain Kihal','wilaya_id' => '46'],
	        ['id' => '523','nom' => 'Aïn Témouchent','wilaya_id' => '46'],
	        ['id' => '524','nom' => 'Beni Saf','wilaya_id' => '46'],
	        ['id' => '525','nom' => 'El Amria','wilaya_id' => '46'],
	        ['id' => '526','nom' => 'El Malah','wilaya_id' => '46'],
	        ['id' => '527','nom' => 'Hammam Bou Hadjar','wilaya_id' => '46'],
	        ['id' => '528','nom' => 'Oulhaça El Gheraba','wilaya_id' => '46'],
	        ['id' => '529','nom' => 'Ghardaïa','wilaya_id' => '47'],
	        ['id' => '530','nom' => 'El Meniaa','wilaya_id' => '47'],
	        ['id' => '531','nom' => 'Metlili','wilaya_id' => '47'],
	        ['id' => '532','nom' => 'Berriane','wilaya_id' => '47'],
	        ['id' => '533','nom' => 'Daïa Ben Dahoua','wilaya_id' => '47'],
	        ['id' => '534','nom' => 'Mansoura','wilaya_id' => '47'],
	        ['id' => '535','nom' => 'Zelfana','wilaya_id' => '47'],
	        ['id' => '536','nom' => 'Guerrara','wilaya_id' => '47'],
	        ['id' => '537','nom' => 'Bounoura','wilaya_id' => '47'],
	        ['id' => '538','nom' => 'Aïn Tarek','wilaya_id' => '48'],
	        ['id' => '540','nom' => 'Ammi Moussa','wilaya_id' => '48'],
	        ['id' => '541','nom' => 'Djidioua','wilaya_id' => '48'],
	        ['id' => '542','nom' => 'El Hamadna','wilaya_id' => '48'],
	        ['id' => '543','nom' => 'El Matmar','wilaya_id' => '48'],
	        ['id' => '544','nom' => 'Mazouna','wilaya_id' => '48'],
	        ['id' => '545','nom' => 'Mendes','wilaya_id' => '48'],
	        ['id' => '546','nom' => 'Oued Rhiou','wilaya_id' => '48'],
	        ['id' => '547','nom' => 'Ramka','wilaya_id' => '48'],
	        ['id' => '548','nom' => 'Relizane','wilaya_id' => '48'],
	        ['id' => '549','nom' => 'Sidi M\'Hamed Ben Ali','wilaya_id' => '48'],
	        ['id' => '550','nom' => 'Yellel','wilaya_id' => '48'],
	        ['id' => '551','nom' => 'Zemmora','wilaya_id' => '48']
      	];

		DB::table('dairas')->insert($dairas);
    }
}
